### PR TITLE
fix(list): show horizontal scroll in table view.

### PR DESCRIPTION
**Pull request by vikram-raj**
issue: https://github.com/openshiftio/openshift.io/issues/2445

### CODE REVIEW

**Comment by SMahil** [comment]
I don't see this issue in prod-preview at all. Checked on fedora + Mac

**Comment by vikram-raj** [comment]
@SMahil Issue is in current planner master. Check here http://fabric8-planner-f8ui.badger.fabric8.io/ . prod-preview is not updated with current planner master.

**Comment by fabric8cd** [comment]
@vikram-raj fabric8/fabric8-ui:SNAPSHOT-PR-2497-7 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2497-fabric8-planner.badger.fabric8.io

**Comment by rgarg1** [comment]
peek 2018-03-22 14-38

**Comment by vikram-raj** [comment]
>Though the horizontal scrollbar is now visible, there are some issues that need to be addressed.
 Restoring the browser window from full screen to a lower size makes the scrollbar vanish
 Maximizing the page to full-screen shifts the scrollbar to the center of the page

Addressed these issue in https://github.com/fabric8-ui/fabric8-planner/pull/2497/commits/f9c27718a593c728cb8d03d101d23ae1cb42c37f

**Comment by fabric8cd** [comment]
@vikram-raj fabric8/fabric8-ui:SNAPSHOT-PR-2497-10 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2497-fabric8-planner.badger.fabric8.io

**Comment by rgarg1** [comment]
@vikram-raj 

Issues resolved! Approved.

**Comment by fabric8cd** [comment]
@vikram-raj fabric8/fabric8-ui:SNAPSHOT-PR-2497-11 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2497-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@vikram-raj fabric8/fabric8-ui:SNAPSHOT-PR-2497-12 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2497-fabric8-planner.badger.fabric8.io

**Pull request merged**
