### PR TITLE
Planner Bugs

### PR DESCRIPTION
**Pull request by sanbornsen**

### CODE REVIEW

**Comment by nimishamukherjee** [comment]
Fixes https://openshift.io/openshiftio/openshiftio/plan/detail/1541

**Comment by fabric8cd** [comment]
@sanbornsen fabric8/fabric8-ui:SNAPSHOT-PR-2275-1 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2275-fabric8-planner.badger.fabric8.io

**Comment by rgarg1** [comment]
The issue seems fixed now @sanbornsen . Newly added Labels are now displayed in the filter drop-down, but unsorted. The labels must be sorted in the list view, the label drop-down in quick-preview, and in the filter toolbar too.

@vikram-raj fixed a similar sorting issue here: https://github.com/fabric8-ui/fabric8-planner/pull/2261

**Comment by sanbornsen** [comment]
Let's not mixup one issue with another. Sorting elements in filter dropdown is a separate issue. Please merge this if the issue of "newly added label not showing up in the filter section" is fixed.

**Comment by fabric8cd** [comment]
@sanbornsen fabric8/fabric8-ui:SNAPSHOT-PR-2275-2 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2275-fabric8-planner.badger.fabric8.io

**Comment by nimishamukherjee** [comment]
Merging and closing this PR.
Created https://openshift.io/openshiftio/openshiftio/plan/detail/1588 for tracking @rgarg1 's comment on sorting.

**Pull request merged**
