### PR TITLE
add feature-flag on query-module

### PR DESCRIPTION
**Pull request by divyanshiGupta**
<strong>Note: If there are pending changes to the PR, prefix the PR title with "WIP" and add the label "DO NOT MERGE"</strong>

### Mandatory
 - [ ] What does this PR do? 
   - This PR adds internal feature-flag on query-module. 
   - To hide query feature from people outside the organisation, it was necessary to add feature-flag on query-tab in fabric8-ui, the query-tab will be visible to only internal employees so that they are aware of query feature in fabric8-planner and feature flag is added on query-module as well so that they can opt-in for the feature if they want to. 
   - When the user will click on the query-tab they will be asked to opt-in for the internal features.

 -  When beta level feature-flag is selected the user can access all the other features like backlog but query feature will not be available and the user will be asked to opt-in for internal features when they will click on the query-tab.
       
screenshot from 2018-08-08 00-47-00
screenshot from 2018-08-08 00-47-44
screenshot from 2018-08-08 00-47-51

- After the user opts-in for the internal features query feature will be accessible.
screenshot from 2018-08-08 00-48-02
screenshot from 2018-08-08 00-48-18

       

- [ ] What issue/task does this PR references?
       https://openshift.io/openshiftio/Openshift_io/plan/detail/359

- [ ] Are the tests Included?
___
### Optional
- [ ] Is the documentation Included?

- [ ] Are the Release Notes included?

- [ ] @mention(s) to expected reviewer(s) included

### CODE REVIEW

**Comment by alien-ike** [comment]
### Ike Plugins (test-keeper)

Thank you @divyanshiGupta for this contribution!



It appears that no tests have been added or updated in this PR.

Automated tests give us confidence in shipping reliable software. Please add some as part of this change.

If you are an admin or the reviewer of this PR and you are sure that no test is needed then you can use the command `/ok-without-tests` as a comment to make the status green.


Your plugin configuration is stored in the [file](https://github.com/fabric8-ui/fabric8-planner/blob/af7df79b9b9474c8e889621ad7a5d7a609595b2e/.ike-prow/test-keeper.yaml).

**Comment by nimishamukherjee** [comment]
Good work @divyanshiGupta

**Comment by divyanshiGupta** [comment]
Thanks @nimishamukherjee

**Pull request merged**
