### PR TITLE
fix(comments): fix date css in wi comment

### PR DESCRIPTION
**Pull request by SMahil**
https://openshift.io/openshiftio/openshiftio/plan/detail/1907

### CODE REVIEW

**Comment by fabric8cd** [comment]
@SMahil fabric8/fabric8-ui:SNAPSHOT-PR-2470-1 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2470-fabric8-planner.badger.fabric8.io

**Comment by rgarg1** [comment]
dates

**Comment by rgarg1** [comment]
Logged another defect for tracking: https://openshift.io/openshiftio/openshiftio/plan/detail/1912

**Comment by fabric8cd** [comment]
@SMahil fabric8/fabric8-ui:SNAPSHOT-PR-2470-2 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2470-fabric8-planner.badger.fabric8.io

**Pull request merged**
