### PR TITLE
Re-structure less files, classnames

### PR DESCRIPTION
**Pull request by SMahil**
This PR includes:

Restructure LESS files for better structure
Rename classnames according to component name
Add Prefix f8- to classnames
Update styles to match guidelines

### CODE REVIEW

**Comment by SMahil** [comment]
Original PR for this was: #2081

**Comment by vikram-raj** [comment]
[test]

**Comment by SMahil** [comment]
[test]

**Comment by rgarg1** [comment]
@SMahil Tests are passing locally, but failing only in docker. Go ahead with the merge as the issue is likely with setup.

**Comment by SMahil** [comment]
[test]

**Comment by baijum** [comment]
[test]

**Comment by SMahil** [comment]
New PR for this #2138

**Pull request closed without merging**
