### PR TITLE
fix(avatar): fix avatar css as per VD

### PR DESCRIPTION
**Pull request by SMahil**
Fix avatar css as per VD: https://redhat.invisionapp.com/share/Z5DZN33W8#/screens/259992905_QuickPreviewReview04

OSIO Issue: https://openshift.io/openshiftio/openshiftio/plan/detail/1610

### CODE REVIEW

**Comment by fabric8cd** [comment]
@SMahil fabric8/fabric8-ui:SNAPSHOT-PR-2307-1 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2307-fabric8-planner.badger.fabric8.io

**Comment by jarifibrahim** [comment]
@SMahil There seems to be an alignment issue.
plan backlog openshift io 2

**Comment by mindreeper2420** [comment]
Are the avatars be made circular everywhere else they appear, or does this only apply to Planner? Currently, the user’s profile image also appears in the masthead and user profile page.

**Comment by nimishamukherjee** [comment]
@mindreeper2420 currently, we are implementing this within planner.

**Comment by SMahil** [comment]
@jarifibrahim Its already existing in master. I think we need UX refinement for dropdowns and should be considered in separate issue

**Comment by nimishamukherjee** [comment]
Functional tests pass locally.

**Comment by nimishamukherjee** [comment]
Unit tests pass locally. Hence merging the PR

**Comment by rgarg1** [comment]
@jarifibrahim Kindly track the issue via a separate defect in OSIO.

**Comment by jarifibrahim** [comment]
@rgarg1 Filed https://openshift.io/openshiftio/openshiftio/plan/detail/1622

**Comment by vikram-raj** [comment]
In the comment section, user avatar is still in square shape.

**Comment by sunilmalagi** [comment]
Here is the Visual for Assignee Modal:
https://redhat.invisionapp.com/share/Z5DZN33W8#/262702329_05AssigneeModal

**Pull request merged**
