### PR TITLE
Tree exploration

### PR DESCRIPTION
**Pull request by sahil143**
This introduces the tree exploration feature

Note: 
- Show tree is by default enabled
- Title Text is Bold for Workitems matching certain criteria

### CODE REVIEW

**Comment by fabric8cd** [comment]
@sahil143 fabric8/fabric8-ui:SNAPSHOT-PR-2415-4 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2415-fabric8-planner.badger.fabric8.io

**Comment by vikram-raj** [comment]
@sahil143 I am not able to uncheck the show tree checkbox.

**Comment by sahil143** [comment]
@vikram-raj because we don't have the functionality when the `Show Tree` is off.

**Comment by vikram-raj** [comment]
Got it. Thanks @sahil143

**Comment by rgarg1** [comment]
More:

2. Workitem filtering is not applied when an iteration from the iteration tree in the side panel is selected. So, all workitems matching an iterations are being displayed, instead of just Features, tasks and Bugs. 

Selecting an iteration from the active section works fine though.

**Comment by sahil143** [comment]
@rgarg1 
> Some workitems are missing from the view:
> Refer to this space: https://fabric8-ui-fabric8-ui-pr-2415-fabric8-
> planner.badger.fabric8.io/rgarg1/space4test/plan
> and browse to the Requirements section in sidebar. Observe that the feature feat1 is not displaying 
> the two child tasks under it, but only Bug1. 

I think this is the intended behavior because we only get matching workitems and their parents (not their child). Children are loaded on demand. In your case **feat1** has three children that is two tasks and a Bug **bug1**, so for `requirements` query you would get feature and bug as matching workitems and their parents as non-matching workitems not **feat1** children.

>Workitem filtering is not applied when an iteration from the iteration tree in the side panel is >selected. So, all workitems matching an iterations are being displayed, instead of just Features, >tasks and Bugs.

this will be fixed by @nimishamukherjee PR.

**Comment by fabric8cd** [comment]
@sahil143 fabric8/fabric8-ui:SNAPSHOT-PR-2415-7 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2415-fabric8-planner.badger.fabric8.io

**Comment by nimishamukherjee** [comment]
Merging this PR. If needed we will raise another PR for implementing outcome of https://github.com/openshiftio/openshift.io/issues/2044

**Pull request merged**
