### PR TITLE
fix(dataTable) : filter by label now working

### PR DESCRIPTION
**Pull request by divyanshiGupta**
Now Clicking on a Lable in the Tabel View filters the WorkItem List by Label.

Please Refer: https://github.com/openshiftio/openshift.io/issues/2447, https://github.com/openshiftio/openshift.io/issues/2295

Test: Done

### CODE REVIEW

**Comment by divyanshiGupta** [comment]
[test]

**Comment by fabric8cd** [comment]
@divyanshiGupta fabric8/fabric8-ui:SNAPSHOT-PR-2516-2 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2516-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@divyanshiGupta fabric8/fabric8-ui:SNAPSHOT-PR-2516-3 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2516-fabric8-planner.badger.fabric8.io

**Comment by divyanshiGupta** [comment]
Somehow the code that I pushed is not available in the generated snapshots. I have pushed a new commit to rebuild the snapshot.

**Comment by fabric8cd** [comment]
@divyanshiGupta fabric8/fabric8-ui:SNAPSHOT-PR-2516-5 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2516-fabric8-planner.badger.fabric8.io

**Comment by alien-ike** [comment]
### Ike Plugins (test-keeper)

Thank you @divyanshiGupta for this contribution!



It appears that no tests have been added or updated in this PR.

Automated tests give us confidence in shipping reliable software. Please add some as part of this change.

If you are an admin and you are sure that no test is needed then you can use the command `/ok-without-tests` as a comment to make the status green.


For more information please head over to official [documentation](http://arquillian.org/ike-prow-plugins/#_test_keeper_plugin). You can find there how to configure the plugin - for example exclude certain file types so if PR contains only them it won't be checked.

**Comment by divyanshiGupta** [comment]
@Raunak1203 I have made the changes according to the review

**Comment by divyanshiGupta** [comment]
@Raunak1203 it is supposed to be like that. The list is supposed to get filtered by label when we click a label from quick preview as well

**Comment by Raunak1203** [comment]
@divyanshiGupta i am clicking on cross to remove label

**Comment by divyanshiGupta** [comment]
@Raunak1203 fixed

**Comment by Raunak1203** [comment]
@divyanshiGupta please check the assigned label in the detail page , it shows 2 cross

**Comment by fabric8cd** [comment]
@divyanshiGupta fabric8/fabric8-ui:SNAPSHOT-PR-2516-17 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2516-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@divyanshiGupta fabric8/fabric8-ui:SNAPSHOT-PR-2516-18 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2516-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@divyanshiGupta fabric8/fabric8-ui:SNAPSHOT-PR-2516-19 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2516-fabric8-planner.badger.fabric8.io

**Pull request merged**
