### PR TITLE
fix(quick-add): fix dropdown type icon spacing

### PR DESCRIPTION
**Pull request by SMahil**
### [ ] What does this PR do? _[Mandatory]_
Fix icon spacing issues in type dropdown

### [ ] What issue/task does this PR references? _[Mandatory]_
https://github.com/openshiftio/openshift.io/issues/3086

### [ ] Are the tests Included? _[Mandatory]_
NA

#### [ ] Is the documentation Included?
NA

#### [ ] Are the Release Notes included?
NA

#### [ ] Is/Are the @mention(s) to reviewer(s) included
@nimishamukherjee @rgarg1

### CODE REVIEW

**Comment by rgarg1** [comment]
scen fund allignment

**Comment by SMahil** [comment]
[test]

**Comment by jarifibrahim** [comment]
[test]

**Comment by rgarg1** [comment]
LGTM @SMahil

**Pull request merged**
