### PR TITLE
refactor(css): restructure css files

### PR DESCRIPTION
**Pull request by SMahil**
This PR includes:

1. Restructure LESS files for better structure
2. Rename classnames according to component name
3. Add Prefix f8- to classnames
4. Update styles to match guidelines

### CODE REVIEW

**Comment by fabric8cd** [comment]
@SMahil fabric8/fabric8-ui:SNAPSHOT-PR-2081-1 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2081-fabric8-planner.badger.fabric8.io

**Comment by hectorj2f** [comment]
[test]

**Comment by fabric8cd** [comment]
@SMahil fabric8/fabric8-ui:SNAPSHOT-PR-2081-10 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2081-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@SMahil fabric8/fabric8-ui:SNAPSHOT-PR-2081-11 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2081-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@SMahil fabric8/fabric8-ui:SNAPSHOT-PR-2081-12 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2081-fabric8-planner.badger.fabric8.io

**Comment by mindreeper2420** [comment]
just an FYI - fabric8-ui has the prefix as `.f8-`, being that these are all under the fabric8 name. This was done in order to match the organization naming structure. The Code Guidelines has been updated to reflect this.

**Comment by SMahil** [comment]
@mindreeper2420 Thanks for the update Adam. I will make changes accordingly. This PR is still in progress.

**Comment by fabric8cd** [comment]
@SMahil fabric8/fabric8-ui:SNAPSHOT-PR-2081-16 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2081-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@SMahil fabric8/fabric8-ui:SNAPSHOT-PR-2081-17 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2081-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@SMahil fabric8/fabric8-ui:SNAPSHOT-PR-2081-19 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2081-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@SMahil fabric8/fabric8-ui:SNAPSHOT-PR-2081-20 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2081-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@SMahil fabric8/fabric8-ui:SNAPSHOT-PR-2081-22 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2081-fabric8-planner.badger.fabric8.io

**Pull request closed without merging**
