### PR TITLE
fix(event): remove duplicate entry from old value and new value

### PR DESCRIPTION
**Pull request by sahil143**
<strong>Note: If there are pending changes to the PR, prefix the PR title with "WIP" and add the label "DO NOT MERGE"</strong>

### Mandatory
 - [x] What does this PR do? 
fixes  bug in Audit-Trail

- [x] What issue/task does this PR references?

Steps to reproduce bug:
1. Create a new workitem
2. Update a field ex: labels
3. There is no event logged for change in label
4. Update Another field ex: Assignee
5. Both events for Label and Assignee are logged in Timeline simultaneously

- [ ] Are the tests Included?
___
### Optional
- [ ] Is the documentation Included?

- [ ] Are the Release Notes included?

- [ ] @mention(s) to expected reviewer(s) included

### CODE REVIEW

**Comment by alien-ike** [comment]
### Ike Plugins (test-keeper)

Thank you @sahil143 for this contribution!



It appears that no tests have been added or updated in this PR.

Automated tests give us confidence in shipping reliable software. Please add some as part of this change.

If you are an admin or the reviewer of this PR and you are sure that no test is needed then you can use the command `/ok-without-tests` as a comment to make the status green.


Your plugin configuration is stored in the [file](https://github.com/fabric8-ui/fabric8-planner/8661c8402973db950183814f846efed3e32d8036/test-keeper.yml).

**Comment by rgarg1** [comment]
@sahil143 The fix seems to be working well. The issue is not seen anymore. Just add Unit tests.

**Pull request merged**
