### PR TITLE
fix(board-view): fix css issues in board view

### PR DESCRIPTION
**Pull request by SMahil**
Board View Fixes
- Fix wi type font size(OSIO Issue: https://openshift.io/openshiftio/openshiftio/plan/detail/1569 )
- Overwritten user assign avatar css

### CODE REVIEW

**Comment by fabric8cd** [comment]
@SMahil fabric8/fabric8-ui:SNAPSHOT-PR-2277-1 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2277-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@SMahil fabric8/fabric8-ui:SNAPSHOT-PR-2277-2 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2277-fabric8-planner.badger.fabric8.io

**Comment by jarifibrahim** [comment]
If you go directly to `board view` URL, something like https://fabric8-ui-fabric8-ui-pr-2277-fabric8-planner.badger.fabric8.io/ijarif/First_Test_Space/plan/board the user avatar appears too big. If you go from `list view` to `board view` the avatar appears just fine.

useravatar

**Comment by fabric8cd** [comment]
@SMahil fabric8/fabric8-ui:SNAPSHOT-PR-2277-3 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2277-fabric8-planner.badger.fabric8.io

**Pull request merged**
