### PR TITLE
fix(test): update failing UI func tests

### PR DESCRIPTION
**Pull request by ldimaggi**

### CODE REVIEW

**Comment by fabric8cd** [comment]
@ldimaggi fabric8/fabric8-ui:SNAPSHOT-PR-2266-1 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2266-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@ldimaggi fabric8/fabric8-ui:SNAPSHOT-PR-2266-2 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2266-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@ldimaggi fabric8/fabric8-ui:SNAPSHOT-PR-2266-3 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2266-fabric8-planner.badger.fabric8.io

**Comment by ldimaggi** [comment]
Some tests are commented out - the others are:
```
[19:43:40] I/testLogger - 
[19:43:40] I/launcher - 0 instance(s) of WebDriver still running
[19:43:40] I/launcher - chrome #01-0 passed
[19:43:40] I/launcher - chrome #01-1 passed
[19:43:40] I/launcher - chrome #01-2 passed
[19:43:40] I/launcher - chrome #01-3 passed
[19:43:40] I/launcher - chrome #01-4 passed
[19:43:40] I/launcher - chrome #01-5 passed
[19:43:40] I/launcher - chrome #01-6 passed
[19:43:40] I/launcher - chrome #01-7 passed
[19:43:40] I/launcher - chrome #01-8 passed
[19:43:40] I/launcher - chrome #01-9 passed
[19:43:40] I/launcher - chrome #01-10 passed
[19:43:40] I/launcher - chrome #01-11 passed
[19:43:40] I/launcher - chrome #01-12 passed
[19:43:40] I/launcher - chrome #01-13 passed
[19:43:40] I/launcher - chrome #01-14 passed
[19:43:40] I/launcher - chrome #01-15 passed
[19:43:40] I/launcher - chrome #01-16 passed
[19:43:40] I/launcher - chrome #01-17 passed
[19:43:40] I/launcher - chrome #01-18 passed
```

**Comment by fabric8cd** [comment]
@ldimaggi fabric8/fabric8-ui:SNAPSHOT-PR-2266-6 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2266-fabric8-planner.badger.fabric8.io

**Comment by rgarg1** [comment]
Approved

**Comment by rgarg1** [comment]
@nimishamukherjee Pls merge this.

**Comment by fabric8cd** [comment]
@ldimaggi fabric8/fabric8-ui:SNAPSHOT-PR-2266-7 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2266-fabric8-planner.badger.fabric8.io

**Pull request merged**
