### PR TITLE
Add filtering of work items by state and creator

### PR DESCRIPTION
**Pull request by nimishamukherjee**
Fixes https://openshift.io/openshiftio/openshiftio/plan/detail/1598 and https://openshift.io/openshiftio/openshiftio/plan/detail/1599

### CODE REVIEW

**Comment by fabric8cd** [comment]
@nimishamukherjee fabric8/fabric8-ui:SNAPSHOT-PR-2287-1 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2287-fabric8-planner.badger.fabric8.io

**Comment by rgarg1** [comment]
@nimishamukherjee Works like a charm. Just one observation:

If WI-1 (state: Open) has a child WI-2 (state: Resolved), and then I filter all WIs by state Open. The results show the parent WI-1 as expected, but also the child WI-2.

**Comment by rgarg1** [comment]
Also, with the current UI, these filters have no effect in the board view as there all states are always displayed. Shall we disable the state filter in board view?

**Comment by jarifibrahim** [comment]
@nimishamukherjee Filter by `workitem state` doesn't seem to work in `board view`.

**Comment by nimishamukherjee** [comment]
@rgarg1 @jarifibrahim I have removed the state filter from the board view.

**Comment by nimishamukherjee** [comment]
> If WI-1 (state: Open) has a child WI-2 (state: Resolved), and then I filter all WIs by state Open. The results show the parent WI-1 as expected, but also the child WI-2.

@rgarg1 we need to work with core on this. We can create another issue to track this.

**Comment by fabric8cd** [comment]
@nimishamukherjee fabric8/fabric8-ui:SNAPSHOT-PR-2287-2 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2287-fabric8-planner.badger.fabric8.io

**Comment by rgarg1** [comment]
@nimishamukherjee The state filter is removed from the Board view. Thanks.

@sanbornsen Clicking on labels in board view do not filter Workitems. I remember you fixed a similar bug in the list view.

**Comment by rgarg1** [comment]
@nimishamukherjee @sanbornsen Logged https://openshift.io/openshiftio/openshiftio/plan/detail/1606 to track the filtering issue on Board-view. Go ahead and merge this one please.

**Comment by fabric8cd** [comment]
@nimishamukherjee fabric8/fabric8-ui:SNAPSHOT-PR-2287-3 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2287-fabric8-planner.badger.fabric8.io

**Pull request merged**
