### PR TITLE
fix(quickadd): Fix the order of work item type in quick add

### PR DESCRIPTION
**Pull request by vikram-raj**
issue: https://github.com/openshiftio/openshift.io/issues/2442

### CODE REVIEW

**Comment by fabric8cd** [comment]
@vikram-raj fabric8/fabric8-ui:SNAPSHOT-PR-2504-3 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2504-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@vikram-raj fabric8/fabric8-ui:SNAPSHOT-PR-2504-4 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2504-fabric8-planner.badger.fabric8.io

**Comment by rgarg1** [comment]
Issue still exists @vikram-raj

**Comment by vikram-raj** [comment]
@rgarg1 @Raunak1203 added tests https://github.com/fabric8-ui/fabric8-planner/pull/2504/commits/81f2b98694502d18d76c8badc1bb4ea6b5db27ba

**Comment by fabric8cd** [comment]
@vikram-raj fabric8/fabric8-ui:SNAPSHOT-PR-2504-6 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2504-fabric8-planner.badger.fabric8.io

**Comment by nimishamukherjee** [comment]
@rgarg1 please review - issue has been fixed.

**Comment by rgarg1** [comment]
The issue is fixed.

**Comment by fabric8cd** [comment]
@vikram-raj fabric8/fabric8-ui:SNAPSHOT-PR-2504-9 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2504-fabric8-planner.badger.fabric8.io

**Pull request merged**
