### PR TITLE
fix(workitem-type): added can-construct filter to work item type list

### PR DESCRIPTION
**Pull request by sanbornsen**
see - openshiftio/openshift.io#3447

<strong>Note: If there are pending changes to the PR, prefix the PR title with "WIP" and add the label "DO NOT MERGE"</strong>

### Mandatory
 - [ ] What does this PR do? 

- [ ] What issue/task does this PR references?

- [ ] Are the tests Included?
___
### Optional
- [ ] Is the documentation Included?

- [ ] Are the Release Notes included?

- [ ] @mention(s) to expected reviewer(s) included

### CODE REVIEW

**Comment by alien-ike** [comment]
### Ike Plugins (test-keeper)

Thank you @sanbornsen for this contribution!



It appears that no tests have been added or updated in this PR.

Automated tests give us confidence in shipping reliable software. Please add some as part of this change.

If you are an admin or the reviewer of this PR and you are sure that no test is needed then you can use the command `/ok-without-tests` as a comment to make the status green.


Your plugin configuration is stored in the [file](https://github.com/fabric8-ui/fabric8-planner/2ac7d741939e6b3748d76034129f110a83b52551/test-keeper.yml).

**Comment by Raunak1203** [comment]
@sanbornsen what about the impediment?
screenshot from 2018-05-04 15-00-33

**Comment by kwk** [comment]
> @sanbornsen what about the impediment?

this will be gone when I've merged my backend PR. https://github.com/fabric8-services/fabric8-wit/pull/2078

**Comment by Raunak1203** [comment]
Thanks @kwk

**Comment by kwk** [comment]
@Raunak1203 prod-preview now shows only valid types:

bildschirmfoto von 2018-05-04 14-52-22

**Pull request merged**
