### PR TITLE
fix(runtime): Add AUTH and SSO environment variables

### PR DESCRIPTION
**Pull request by jarifibrahim**
This PR fixes the failures shown in the screenshots below

screenshot from 2017-11-23 17-12-01

screenshot from 2017-11-23 17-15-32

### CODE REVIEW

**Comment by fabric8cd** [comment]
@jarifibrahim fabric8/fabric8-ui:SNAPSHOT-PR-2341-1 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2341-fabric8-planner.badger.fabric8.io

**Comment by sbose78** [comment]
thanks @jarifibrahim - can't believe we 'over thought' this fix for so long :) Good job!

**Comment by nimishamukherjee** [comment]
Good stuff @jarifibrahim

**Comment by sthaha** [comment]
@jarifibrahim good stuff :)

I  tried running the patch but saw a strange behaviour of tokens getting deleted when I am redirected back to the planner page. This seems quite like the behaviour we saw on production last well where the tokens were getting deleted by the landing page (openshift.io) . 


planner-deletes-token

**Comment by fabric8cd** [comment]
@jarifibrahim fabric8/fabric8-ui:SNAPSHOT-PR-2341-7 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2341-fabric8-planner.badger.fabric8.io

**Pull request merged**
