### PR TITLE
fix(quick add): Reset work item context when a work item is deselected.

### PR DESCRIPTION
**Pull request by nimishamukherjee**
Reset work item context when a work item is deselected. Fixes [OSIO-1549](https://openshift.io/openshiftio/openshiftio/plan/detail/1549)

### CODE REVIEW

**Comment by fabric8cd** [comment]
@nimishamukherjee fabric8/fabric8-ui:SNAPSHOT-PR-2311-1 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2311-fabric8-planner.badger.fabric8.io

**Comment by jarifibrahim** [comment]
This is @vikram-raj's comment on the [OSIO-1549](https://openshift.io/openshiftio/openshiftio/plan/detail/1549)  issue

> It is a valid behavior. Because you select the papercuts work item so only value proposition and experience can be the child of the papercuts. The problem here is UX is not good for this. That's why it is confusing.

Does the issue exists or it is the intended behaviour?

**Comment by nimishamukherjee** [comment]
@jarifibrahim the comment given by @vikram-raj is true. Have a look at https://github.com/openshiftio/openshift.io/issues/331. This explains the quick add work item type behaviour.

If the user clicks on Portfolio, the quick add options are
Scenario, Fundamental, and Papercuts
If a scenario, fundamental, or papercut is selected, the quick add options are Value Proposition and Experience.
This behaviour continues down the hierarchy

sdd

Note: Currently we have restricted bug at requirements level only.

**Comment by jarifibrahim** [comment]
@nimishamukherjee Looks like the issue still exists

peek 2017-10-26 23-48

**Comment by fabric8cd** [comment]
@nimishamukherjee fabric8/fabric8-ui:SNAPSHOT-PR-2311-2 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2311-fabric8-planner.badger.fabric8.io

**Comment by nimishamukherjee** [comment]
@jarifibrahim please verify the fix now.

**Comment by fabric8cd** [comment]
@nimishamukherjee fabric8/fabric8-ui:SNAPSHOT-PR-2311-3 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2311-fabric8-planner.badger.fabric8.io

**Pull request merged**
