### PR TITLE
fix(inline-title): parse special character before render in UI

### PR DESCRIPTION
**Pull request by vikram-raj**
### [ ] What does this PR do? _[Mandatory]_
_Note: If you are still working on the changes, prefix the PR title with "WIP" and add the label "DO NOT MERGE"_

 - Added a function to convert the special character. 
 - Remove innerHTML from inlineInput component.
 - Fix test.

### [ ] What issue/task does this PR references? _[Mandatory]_

https://github.com/openshiftio/openshift.io/issues/3362

### [ ] Are the tests Included? _[Mandatory]_

NA

### CODE REVIEW

**Comment by alien-ike** [comment]
### Ike Plugins (test-keeper)

Thank you @vikram-raj for this contribution!



It appears that no tests have been added or updated in this PR.

Automated tests give us confidence in shipping reliable software. Please add some as part of this change.

If you are an admin or the reviewer of this PR and you are sure that no test is needed then you can use the command `/ok-without-tests` as a comment to make the status green.


Your plugin configuration is stored in the [file](https://github.com/fabric8-ui/fabric8-planner/75629e4bc5c7d9fd128405896bf9b7d3b96914d2/test-keeper.yml).

**Comment by vikram-raj** [comment]
A test was already added here https://github.com/fabric8-ui/fabric8-planner/pull/2518 for check of special character.

**Comment by nimishamukherjee** [comment]
[test]

**Comment by vikram-raj** [comment]
[test]

**Comment by jarifibrahim** [comment]
[test]

**Pull request merged**
