### PR TITLE
Spinner wait overlay for list view

### PR DESCRIPTION
**Pull request by michaelkleinhenz**
This adds an overlay spinner when data is being loaded into the list view. It also includes overlays for the sidebar and the complete interface (only for list view for now as the board view need refactoring to do something similar).

### CODE REVIEW

**Comment by fabric8cd** [comment]
@michaelkleinhenz fabric8/fabric8-ui:SNAPSHOT-PR-2195-1 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2195-fabric8-planner.badger.fabric8.io

**Comment by michaelkleinhenz** [comment]
Note: the overlay and the overlay API for the board view is in this PR, it is just not used yet for context switches (it is used though for the initial load of the board view).

**Comment by fabric8cd** [comment]
@michaelkleinhenz fabric8/fabric8-ui:SNAPSHOT-PR-2195-2 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2195-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@michaelkleinhenz fabric8/fabric8-ui:SNAPSHOT-PR-2195-3 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2195-fabric8-planner.badger.fabric8.io

**Comment by michaelkleinhenz** [comment]
@nimishamukherjee fixed. :-)

**Comment by fabric8cd** [comment]
@michaelkleinhenz fabric8/fabric8-ui:SNAPSHOT-PR-2195-4 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2195-fabric8-planner.badger.fabric8.io

**Pull request merged**
