### PR TITLE
WIP - Standalone planner CI

### PR DESCRIPTION
**Pull request by pranavgore09**
review NOT required as of now

The aim is to create a snapshot for the standalone planner.

nothing was done on CD
build on top of Michael's standalone branch `new-header`

### CODE REVIEW

**Comment by fabric8cd** [comment]
@pranavgore09 fabric8/fabric8-planner:standalone is deployed and available for testing at https://fabric8-planner-fabric8-planner-pr-2393-fabric8-planner.badger.fabric8.io

**Comment by pranavgore09** [comment]
This PR is to be closed after success at https://github.com/fabric8-ui/fabric8-planner/pull/2426

**Comment by alien-ike** [comment]
### Ike Plugins (test-keeper)

Thank you @pranavgore09 for this contribution!



It appears that no tests have been added or updated in this PR.

Automated tests give us confidence in shipping reliable software. Please add some as part of this change.

If you are an admin and you are sure that no test is needed then you can use the command `/ok-without-tests` as a comment to make the status green.


For more information please head over to official [documentation](http://arquillian.org/ike-prow-plugins/#_test_keeper_plugin). You can find there how to configure the plugin - for example exclude certain file types so if PR contains only them it won't be checked.

**Comment by pranavgore09** [comment]
closing in favor of `release from cico` already in master

**Pull request closed without merging**
