### PR TITLE
New UI for Assignee dropdown

### PR DESCRIPTION
**Pull request by SMahil**
- Add new UI to assignee dropdown
- Match UI with multiple selector dropdown

### CODE REVIEW

**Comment by fabric8cd** [comment]
@SMahil fabric8/fabric8-ui:SNAPSHOT-PR-2355-4 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2355-fabric8-planner.badger.fabric8.io

**Comment by jarifibrahim** [comment]
@SMahil These tests also have to be updated https://github.com/fabric8-ui/fabric8-planner/blob/b9bfba4d3eb0ca9e36e77c06d77a8fe4f7fc1269/runtime/src/tests/work-item/work-item-list/assign.spec.js

**Comment by fabric8cd** [comment]
@SMahil fabric8/fabric8-ui:SNAPSHOT-PR-2355-5 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2355-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@SMahil fabric8/fabric8-ui:SNAPSHOT-PR-2355-6 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2355-fabric8-planner.badger.fabric8.io

**Comment by rgarg1** [comment]
- Video to show the patch request to backend:
https://drive.google.com/open?id=1wrwL1pYyqcwfK2ETxvR0_biG5eQGdPXg

- Screenshot to display the filter results:
assignee filter

- Screenshot to display the odd assignee icon:
add assignee icon

**Comment by fabric8cd** [comment]
@SMahil fabric8/fabric8-ui:SNAPSHOT-PR-2355-7 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2355-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@SMahil fabric8/fabric8-ui:SNAPSHOT-PR-2355-9 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2355-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@SMahil fabric8/fabric8-ui:SNAPSHOT-PR-2355-10 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2355-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@SMahil fabric8/fabric8-ui:SNAPSHOT-PR-2355-11 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2355-fabric8-planner.badger.fabric8.io

**Comment by sanbornsen** [comment]
@rgarg1 On "Opening and closing the assignee drop-list send a PATCH request to the backend. This is even when no edits were made. This is bad." - this is a common behavior for select-dropdown component which should be fixed in the component. This PR has nothing to do with it. I'll fix it in the main component. This PR is good to go.

**Comment by rgarg1** [comment]
Based on @sanbornsen comments, approving this PR. Good to go! I'll track the component specific issue in a separate defect.

**Comment by rgarg1** [comment]
What about the icon though?

**Comment by SMahil** [comment]
@rgarg1 icon has been fixed.
screen shot 2017-12-13 at 4 25 02 pm

**Pull request merged**
