### PR TITLE
fix(test): Fix the filter drop down

### PR DESCRIPTION
**Pull request by nimishamukherjee**
- Update mock filter data a
- enable default url for inmemory mode
- fix creator filter
- fix area filter
- fix state filter

### CODE REVIEW

**Comment by nimishamukherjee** [comment]
@jarifibrahim @Raunak1203 this PR fixes the filter drop down.
Only the Work Item Type filter works.

**Comment by nimishamukherjee** [comment]
@jarifibrahim what does the URL look like?
Any console errors?

**Comment by jarifibrahim** [comment]
@nimishamukherjee 
screenshot from 2018-02-20 14-18-12
screenshot from 2018-02-20 14-18-52

**Comment by fabric8cd** [comment]
@nimishamukherjee fabric8/fabric8-ui:SNAPSHOT-PR-2441-3 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2441-fabric8-planner.badger.fabric8.io

**Comment by nimishamukherjee** [comment]
@jarifibrahim please check now.

**Comment by Raunak1203** [comment]
filter by state is working now.
@nimishamukherjee will the other filters: Filter By assignee, label and title will also be supported in inmemory mode?

**Comment by nimishamukherjee** [comment]
@Raunak1203 filter by assignee will work.
Filter by Label and Title need some work and I will raise a separate PR for them.

**Comment by fabric8cd** [comment]
@nimishamukherjee fabric8/fabric8-ui:SNAPSHOT-PR-2441-6 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2441-fabric8-planner.badger.fabric8.io

**Comment by jarifibrahim** [comment]
https://github.com/fabric8-ui/fabric8-planner/pull/2441/commits/c006562a58db564db7c07bbac41b4f35ce71263d fixes https://github.com/openshiftio/openshift.io/issues/2374

**Pull request merged**
