### PR TITLE
fix(iteration): iteration date selector only allows selecting past dates

### PR DESCRIPTION
**Pull request by vikram-raj**
issue: https://github.com/openshiftio/openshift.io/issues/2506

### CODE REVIEW

**Comment by fabric8cd** [comment]
@vikram-raj fabric8/fabric8-ui:SNAPSHOT-PR-2500-3 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2500-fabric8-planner.badger.fabric8.io

**Comment by rgarg1** [comment]
@vikram-raj The issue specified is fixed and now user can select any date for an iteration.

However, there is a side effect noticed:
1) Select start and end dates for an iteration and save it
2) Open the iteration again and clear the dates using the 'x' icon
3) Try saving the iteration. Observe that error is displayed "Some error has occured on updating iteration
"

**Comment by vikram-raj** [comment]
> However, there is a side effect noticed:
Select start and end dates for an iteration and save it
Open the iteration again and clear the dates using the 'x' icon
Try saving the iteration. Observe that error is displayed "Some error has occurred on updating iteration
"

@rgarg1 I handled this case in UI. But backend doesn't support empty start and end date. So backend needs to support this then only we can go forward with this PR.  **cc**: @pranavgore09

**Comment by fabric8cd** [comment]
@vikram-raj fabric8/fabric8-ui:SNAPSHOT-PR-2500-7 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2500-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@vikram-raj fabric8/fabric8-ui:SNAPSHOT-PR-2500-8 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2500-fabric8-planner.badger.fabric8.io

**Comment by rgarg1** [comment]
Once the backend support is ready, we also need to add tests to validate the functionality.

**Comment by vikram-raj** [comment]
@rgarg1 I will do the reset start and end date of iteration in separate PR. As this PR is only fixed https://github.com/openshiftio/openshift.io/issues/2506 and https://github.com/openshiftio/openshift.io/issues/1831

**Comment by rgarg1** [comment]
@vikram-raj LGTM

**Pull request merged**
