### PR TITLE
fix(tests): Use Headless Chrome instead of PhantomJS for unit tests

### PR DESCRIPTION
**Pull request by jarifibrahim**
`npm install` is **3x** faster without PhantomJS. The time reduced from `96` secs to `30` secs when running locally.

NOTE - I have no clue about the 1442 deletions in the package-lock.json file.

### CODE REVIEW

**Comment by fabric8cd** [comment]
@jarifibrahim fabric8/fabric8-ui:SNAPSHOT-PR-2459-2 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2459-fabric8-planner.badger.fabric8.io

**Comment by debloper** [comment]
> I have no clue about the 1442 deletions in the package-lock.json file.

Butterfly effect of PhantomJS removal, no need to worry.
Also, in order to resolve conflict in `package-lock.json`, your change should be prioritized over incoming changes.

**Comment by fabric8cd** [comment]
@jarifibrahim fabric8/fabric8-ui:SNAPSHOT-PR-2459-3 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2459-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@jarifibrahim fabric8/fabric8-ui:SNAPSHOT-PR-2459-7 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2459-fabric8-planner.badger.fabric8.io

**Pull request merged**
