### PR TITLE
fixed changes due to rebase conflict

### PR DESCRIPTION
**Pull request by divyanshiGupta**
This PR was raised by Sukhvir https://github.com/fabric8-ui/fabric8-planner/pull/2477/files#diff-dbc24aee843bca8262d1c28fbaf591ccL262
And this was my PR 899b1f4#diff-dbc24aee843bca8262d1c28fbaf591ccL291 but somehow some change got lost because of some merge issue. 
That is why I have added back the change that got lost and raised the PR again.

### CODE REVIEW

**Comment by divyanshiGupta** [comment]
@nimishamukherjee Can you merge this one?

**Comment by nimishamukherjee** [comment]
@divyanshiGupta which issue does this fix?

**Comment by fabric8cd** [comment]
@divyanshiGupta fabric8/fabric8-ui:SNAPSHOT-PR-2591-2 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2591-fabric8-planner.badger.fabric8.io

**Comment by divyanshiGupta** [comment]
@nimishamukherjee It doesn't solve any current major issue. Its just some code that got lost between merges. Thats what i've added in this PR so that nothing breaks because of the lost piece of code.

**Comment by nimishamukherjee** [comment]
@divyanshiGupta merging this PR. Going forward please be do not raise such PRs.
Merge conflicts need to be handled correctly.

**Pull request merged**
