### PR TITLE
fix(filter-values): filter values sorted alphabetically

### PR DESCRIPTION
**Pull request by divyanshiGupta**
Fixes https://github.com/openshiftio/openshift.io/issues/3642

Assignees & Creators, Areas, Labels, Iterations are sorted alphabetically in all dropdowns

### CODE REVIEW

**Comment by alien-ike** [comment]
### Ike Plugins (test-keeper)

Thank you @divyanshiGupta for this contribution!



It appears that no tests have been added or updated in this PR.

Automated tests give us confidence in shipping reliable software. Please add some as part of this change.

If you are an admin or the reviewer of this PR and you are sure that no test is needed then you can use the command `/ok-without-tests` as a comment to make the status green.


For more information please head over to official [documentation](http://arquillian.org/ike-prow-plugins/#_test_keeper_plugin). You can find there how to configure the plugin.

**Comment by sanbornsen** [comment]
Do we only sort the filter values or also dropdowns in other places? For example assignees, iterations, areas and labels drop-down in quick preview or details page?

**Comment by rgarg1** [comment]
@sanbornsen @divyanshiGupta The expectation is that all dropdowns should be sorted.

**Comment by divyanshiGupta** [comment]
@sanbornsen @rgarg1 assignees and areas are sorted in every dropdown

**Comment by divyanshiGupta** [comment]
@rgarg1 do we need to sort iteration dropdown also? It was not mentioned in the issue. If yes can you please update the issue?

**Comment by divyanshiGupta** [comment]
@sanbornsen @rgarg1 I have added sorting of iterations and labels in quick-preview and detail page dropdowns but currently I am not sure how to test it. If you guys have any ideas how to test it in a good way, that will be helpful.

**Comment by rgarg1** [comment]
Yes @divyanshiGupta. Iteration need to be sorted too. Thanks for fixing that.

**Comment by rgarg1** [comment]
@divyanshiGupta 

All drop-downs appear fixed with your PR, except the _iterations_. This is how it appears in my space:

iter sorting prob

**Comment by divyanshiGupta** [comment]
@rgarg1 I am sorting it on the basis of the value property of iteration, and it is the entire path of the iteration and not just the name of the iteration. I am looking into it to sort it in a better way.

**Comment by divyanshiGupta** [comment]
@rgarg1 can you verify if it works for you now?

**Comment by rgarg1** [comment]
No change @divyanshiGupta

**Comment by divyanshiGupta** [comment]
@rgarg1 looking into it

**Comment by rgarg1** [comment]
@divyanshiGupta Pls re-apply the _ready for review_ label once the iteration dropdown is fixed.

**Comment by rgarg1** [comment]
The drop-downs are sorted. Just add the tests before the PR could be merged.

**Comment by divyanshiGupta** [comment]
@rgarg1 sure. Working on it

**Comment by rgarg1** [comment]
@Raunak1203 Your review on UI tests is requested.

**Comment by rgarg1** [comment]
LGTM

**Pull request merged**
