### PR TITLE
fix(table-view): fix icon sizes and add tooltips

### PR DESCRIPTION
**Pull request by SMahil**
https://openshift.io/openshiftio/openshiftio/plan/detail/1944

### CODE REVIEW

**Comment by vikram-raj** [comment]
@SMahil No need to make any changes in components of the components folder. Because we are not using the components of the components folder.

**Comment by debloper** [comment]
As mentioned by @vikram-raj, you can safely ignore/discard the changes in `components` folder. It'll soon be deprecated in favor of `components_ngrx`.

**Comment by fabric8cd** [comment]
@SMahil fabric8/fabric8-ui:SNAPSHOT-PR-2503-8 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2503-fabric8-planner.badger.fabric8.io

**Comment by jarifibrahim** [comment]
[test]

**Comment by rgarg1** [comment]
@SMahil A separate icon to open Quick-preview is now removed. Rest of the buttons and tooltips look fine.

**Comment by fabric8cd** [comment]
@SMahil fabric8/fabric8-ui:SNAPSHOT-PR-2503-19 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2503-fabric8-planner.badger.fabric8.io

**Pull request merged**
