### PR TITLE
[WIP] fix(toast-notifications): Suppress create and update notifications (git-1554)

### PR DESCRIPTION
**Pull request by nimishamukherjee**
### Mandatory
 Suppress toast notifications for:
- create and update of work items
- create and update of iterations
- create of custom filters

What issue/task does this PR references?
https://github.com/openshiftio/openshift.io/issues/1554

Are the tests Included?
No

### CODE REVIEW

**Comment by alien-ike** [comment]
### Ike Plugins (test-keeper)

Thank you @nimishamukherjee for this contribution!



It appears that no tests have been added or updated in this PR.

Automated tests give us confidence in shipping reliable software. Please add some as part of this change.

If you are an admin or the reviewer of this PR and you are sure that no test is needed then you can use the command `/ok-without-tests` as a comment to make the status green.


Your plugin configuration is stored in the [file](https://github.com/fabric8-ui/fabric8-planner/82faba69b1fc56c9271a9f6b336f81929fee9498/test-keeper.yml).

**Comment by jarifibrahim** [comment]
[test]

**Comment by Raunak1203** [comment]
[test]

**Comment by nimishamukherjee** [comment]
Removed the commented code @kpiwko

**Comment by Raunak1203** [comment]
[test]

**Comment by kpiwko** [comment]
Thanks a lot @nimishamukherjee and @Raunak1203 !

**Comment by Raunak1203** [comment]
[test]

**Comment by Raunak1203** [comment]
This PR is blocked by issue https://github.com/openshiftio/openshift.io/issues/3028

**Comment by Raunak1203** [comment]
issue https://github.com/openshiftio/openshift.io/issues/3028 is fixed with PR https://github.com/fabric8-ui/fabric8-planner/pull/2675

**Pull request closed without merging**
