### PR TITLE
fix(list view): Introduce parent details in the list view.

### PR DESCRIPTION
**Pull request by nimishamukherjee**
Introduce parent information on the list view.
Visual design - https://redhat.invisionapp.com/share/YZDOM6S2R#/screens
Visual design with specs - https://redhat.invisionapp.com/share/YZDOM6S2R#/screens/255484840
Visual design for indentation - https://redhat.invisionapp.com/share/XQDLTAHCY#/screens/260232204

### CODE REVIEW

**Comment by fabric8cd** [comment]
@nimishamukherjee fabric8/fabric8-ui:SNAPSHOT-PR-2291-9 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2291-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@nimishamukherjee fabric8/fabric8-ui:SNAPSHOT-PR-2291-10 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2291-fabric8-planner.badger.fabric8.io

**Comment by jarifibrahim** [comment]
@nimishamukherjee Take a look at this.
abc

**Comment by rgarg1** [comment]
@nimishamukherjee This looks like a bug 
super expanded list view

**Comment by rgarg1** [comment]
@nimishamukherjee and this too
escaped chars in immediate parent title

**Comment by rgarg1** [comment]
The tool-tip for the workitem's type of the parent is showing like this:
wit of immediate parent tooltip

**Comment by rgarg1** [comment]
@nimishamukherjee Can we show the quick-preview of the immediate parent instead of the detail view, when the user clicks on the immediate parent ID? What does UX has to say about this?

**Comment by rgarg1** [comment]
@nimishamukherjee We need a UX review too.

**Comment by jarifibrahim** [comment]
Missing WI type icon
abc1

**Comment by rgarg1** [comment]
One more issue. The Workitem type icon goes missing in the iteration context:

taskx-3 in list view - iteration

**Comment by jarifibrahim** [comment]
@nimishamukherjee This looks broken to me. I see `Task 2` 3 times.
Also, the `Task 2` has 2 parents. But only one shows up in the first entry.

abc1

**Comment by rgarg1** [comment]
Any WI cannot have two parents. Its missing a check.

**Comment by fabric8cd** [comment]
@nimishamukherjee fabric8/fabric8-ui:SNAPSHOT-PR-2291-11 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2291-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@nimishamukherjee fabric8/fabric8-ui:SNAPSHOT-PR-2291-14 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2291-fabric8-planner.badger.fabric8.io

**Comment by nimishamukherjee** [comment]
> @nimishamukherjee Can we show the quick-preview of the immediate parent instead of the detail view, when the user clicks on the immediate parent ID? What does UX has to say about this?

@rgarg1 checked with UX on this. The parent needs to open in detailed view.

**Comment by nimishamukherjee** [comment]
> @nimishamukherjee This looks broken to me. I see Task 2 3 times.
Also, the Task 2 has 2 parents. But only one shows up in the first entry.

This is a backend issue and @kwk is looking in to this. We could create an issue for the UI also, disable parent linking if the work item already has a parent.

**Comment by rgarg1** [comment]
**Issues I see:**

1) Child workitems when expanded, should be indented a little right to the parent. E.g. WI 25 in the attached image

2) The assignee icon for myself is often displayed differently. See second image.

3) The duplicate WI issue persists.

indent_issue

assignee icon

**Comment by rgarg1** [comment]
@nimishamukherjee Reviewed!

**Comment by nimishamukherjee** [comment]
> Child workitems when expanded, should be indented a little right to the parent. E.g. WI 25 in the attached image

@SMahil will fix this in a separate PR as we got the designs today from UX and she is on PTO tomorrow.

>     The assignee icon for myself is often displayed differently. See second image.

Create a separate issue for this as this is not related to this PR.

>     The duplicate WI issue persists.
Please refer to our Cabal discussion - https://docs.google.com/document/d/17LdWVYXoR4CXZUsRMq5qzpicQ49Yr0nR79lMYAumYIk/edit
The second topic addressed by me. Have a look at the comments.
Pasting the same here
Checked with Samir and he confirmed the following behaviour.
If we have a structure like
A
--B (B is a child of A)
C
--D (D is a child of C)
If we query by All work item types,
we should get
▸ A
B
▸ C
D

Clicking on A or C would take the user in to exploration mode and would display B again
▾ A
B
B
▾ C
D
D

**Comment by fabric8cd** [comment]
@nimishamukherjee fabric8/fabric8-ui:SNAPSHOT-PR-2291-15 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2291-fabric8-planner.badger.fabric8.io

**Comment by rgarg1** [comment]
@nimishamukherjee 
Although I've my reservations against displaying a workitem twice, but since its approved by UX, lets mode ahead. BTW, has the behavior changed since I last looked at the preview?

Do we already have a defect to track the indentation issue or should I log one?

**Comment by nimishamukherjee** [comment]
Work items created to track issues on this PR
- Multiple parents for a work item (backend fix in progress) - https://openshift.io/openshiftio/openshiftio/plan/detail/1609
- Indentation for child work items - https://openshift.io/openshiftio/openshiftio/plan/detail/1618
- Variations in assignee icon for the logged in user - https://openshift.io/openshiftio/openshiftio/plan/detail/1619

**Comment by nimishamukherjee** [comment]
@rgarg1 the behaviour has not changes.
Please make a note of the issues that are being tracked.

**Comment by fabric8cd** [comment]
@nimishamukherjee fabric8/fabric8-ui:SNAPSHOT-PR-2291-16 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2291-fabric8-planner.badger.fabric8.io

**Comment by kwk** [comment]
@nimishamukherjee  and @rgarg1 FYI we should no longer have multiple parent links in production and we should no longer be able to produce one of them.

**Pull request merged**
