### PR TITLE
Dont Merge : Build CI without running tests

### PR DESCRIPTION
**Pull request by pranavgore09**
Intent is to run 10 builds without unit or functional tests and then check success rate of the builds

### CODE REVIEW

**Comment by fabric8cd** [comment]
@pranavgore09 fabric8/fabric8-ui:SNAPSHOT-PR-2442-3 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2442-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@pranavgore09 fabric8/fabric8-ui:SNAPSHOT-PR-2442-6 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2442-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@pranavgore09 fabric8/fabric8-ui:SNAPSHOT-PR-2442-8 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2442-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@pranavgore09 fabric8/fabric8-ui:SNAPSHOT-PR-2442-9 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2442-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@pranavgore09 fabric8/fabric8-ui:SNAPSHOT-PR-2442-10 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2442-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@pranavgore09 fabric8/fabric8-ui:SNAPSHOT-PR-2442-11 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2442-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@pranavgore09 fabric8/fabric8-ui:SNAPSHOT-PR-2442-12 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2442-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@pranavgore09 fabric8/fabric8-ui:SNAPSHOT-PR-2442-13 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2442-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@pranavgore09 fabric8/fabric8-ui:SNAPSHOT-PR-2442-14 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2442-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@pranavgore09 fabric8/fabric8-ui:SNAPSHOT-PR-2442-15 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2442-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@pranavgore09 fabric8/fabric8-ui:SNAPSHOT-PR-2442-16 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2442-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@pranavgore09 fabric8/fabric8-ui:SNAPSHOT-PR-2442-17 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2442-fabric8-planner.badger.fabric8.io

**Comment by alien-ike** [comment]
### Ike Plugins (test-keeper)

Thank you @pranavgore09 for this contribution!



It appears that no tests have been added or updated in this PR.

Automated tests give us confidence in shipping reliable software. Please add some as part of this change.

If you are an admin and you are sure that no test is needed then you can use the command `/ok-without-tests` as a comment to make the status green.


For more information please head over to official [documentation](http://arquillian.org/ike-prow-plugins/#_test_keeper_plugin). You can find there how to configure the plugin - for example exclude certain file types so if PR contains only them it won't be checked.

**Comment by pranavgore09** [comment]
closing in favor of `release from cico` already in master

**Pull request closed without merging**
