### PR TITLE
fix(tests): Add datatable tests

### PR DESCRIPTION
**Pull request by jarifibrahim**
screenshot from 2018-01-18 12-22-05

### CODE REVIEW

**Comment by fabric8cd** [comment]
@jarifibrahim fabric8/fabric8-ui:SNAPSHOT-PR-2395-1 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2395-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@jarifibrahim fabric8/fabric8-ui:SNAPSHOT-PR-2395-6 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2395-fabric8-planner.badger.fabric8.io

**Comment by jarifibrahim** [comment]
The test behaves differently on different screen sizes. This needs to fixed.

**Comment by jarifibrahim** [comment]
Closing this PR since we'll be using Typescript based tests https://github.com/fabric8-ui/fabric8-planner/pull/2417 which makes this PR obsolete.

**Comment by fabric8cd** [comment]
@jarifibrahim fabric8/fabric8-ui:SNAPSHOT-PR-2395-7 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2395-fabric8-planner.badger.fabric8.io

**Pull request closed without merging**
