### PR TITLE
fix(work-item-create-selector): Give clickable elements a pointer cursor

### PR DESCRIPTION
**Pull request by jarifibrahim**

### CODE REVIEW

**Comment by sbose78** [comment]
[test]

**Comment by SMahil** [comment]
@jarifibrahim I am adding common class cursor in PR: https://github.com/fabric8-ui/fabric8-planner/pull/2177.

Wait for that and just add cursor class. We don't need to add separate css for that.
Either I will add these changes in same PR

**Comment by jarifibrahim** [comment]
Closing this since https://github.com/fabric8-ui/fabric8-planner/pull/2177 fixes the issue https://openshift.io/openshiftio/openshiftio/plan/detail/1553.

**Comment by fabric8cd** [comment]
@jarifibrahim fabric8/fabric8-ui:SNAPSHOT-PR-2267-2 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2267-fabric8-planner.badger.fabric8.io

**Pull request closed without merging**
