### PR TITLE
fix(patternfly): update PatternFly dependency

### PR DESCRIPTION
**Pull request by mindreeper2420**
update PatternFly dependency to 3.26.1, matching fabric8-ui

### CODE REVIEW

**Comment by fabric8cd** [comment]
@mindreeper2420 fabric8/fabric8-ui:SNAPSHOT-PR-2093-1 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2093-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@mindreeper2420 fabric8/fabric8-ui:SNAPSHOT-PR-2093-4 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2093-fabric8-planner.badger.fabric8.io

**Comment by SMahil** [comment]
I approved these changes

**Comment by fabric8cd** [comment]
@mindreeper2420 fabric8/fabric8-ui:SNAPSHOT-PR-2093-5 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2093-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@mindreeper2420 fabric8/fabric8-ui:SNAPSHOT-PR-2093-6 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2093-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@mindreeper2420 fabric8/fabric8-ui:SNAPSHOT-PR-2093-7 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2093-fabric8-planner.badger.fabric8.io

**Pull request merged**
