### PR TITLE
feat(deploy): run f8ui integrated planner on docker compose stack

### PR DESCRIPTION
**Pull request by debloper**
Integration build with upstream source(s):
```bash
cd /path/to/planner/repo
./scripts/bootstrap.sh
```

Integration build with local source(s):
```bash
bootstrap.sh --planner=/full/path/to/planner --platform=/full/path/to/platform
# it's okay to provide local path to both repos, either repo or none
# if path was not provided to either, that repo will be cloned from upstream
```

To ignore builds and dry-run the orchestration, use `--dryrun` flag:
```bash
bootstrap.sh --dryrun
# skips building planner library and f8ui
# generates a mock index.html file
```

N.B: depends on fabric8-ui/fabric8-ui#2178 to function.

### CODE REVIEW

**Comment by jarifibrahim** [comment]
@debloper on running `bootstrap.sh` I get the "Welcome to nginx" page. Looks like some files are not being copied to the required folder.

**Comment by debloper** [comment]
@jarifibrahim hopefully this works now (for the time being, not a complete fix).
Please give it a try and confirm if this fixes for you or it doesn't.

In case it doesn't fix the issue, please post the `stdout` for the part starting where it says:
```
Copy over the build artifacts from container to host...

This is only needed because the platform build executes `npm run clean`
which removes the `dist` directory from the host, unlinking the volume
```
until where it says:
```
Generating f8ui integrated planner image from build artifacts...
```

**Comment by fabric8cd** [comment]
@debloper fabric8/fabric8-ui:SNAPSHOT-PR-2309-3 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2309-fabric8-planner.badger.fabric8.io

**Comment by jarifibrahim** [comment]
@debloper It isn't working. 
```
+ echo 'Copy over the build artifacts from container to host...'
Copy over the build artifacts from container to host...
+ echo ''

++ npm run clean
+ echo 'This is only needed because the platform build executes 
> fabric8-ui@0.0.0-development clean /tmp/platform
> npm cache verify && npm run rimraf -- node_modules doc coverage dist

Cache verified and compressed (~/.npm/_cacache):
Content verified: 1853 (147123240 bytes)
Content garbage-collected: 20 (1540223 bytes)
Index entries: 2317
Finished in 2.773s

> fabric8-ui@0.0.0-development rimraf /tmp/platform
> rimraf "node_modules" "doc" "coverage" "dist"'
This is only needed because the platform build executes 
> fabric8-ui@0.0.0-development clean /tmp/platform
> npm cache verify && npm run rimraf -- node_modules doc coverage dist

Cache verified and compressed (~/.npm/_cacache):
Content verified: 1853 (147123240 bytes)
Content garbage-collected: 20 (1540223 bytes)
Index entries: 2317
Finished in 2.773s

> fabric8-ui@0.0.0-development rimraf /tmp/platform
> rimraf "node_modules" "doc" "coverage" "dist"
++ dist
./scripts/bootstrap.sh: line 103: dist: command not found
+ echo 'which removes the  directory from the host, unlinking the volume'
which removes the  directory from the host, unlinking the volume
+ docker exec -u root fabric8-ui-builder cp -r /home/fabric8/fabric8-ui/dist /
cp: cannot create regular file ‘/dist/humans.txt’: No such file or directory
cp: cannot create regular file ‘/dist/robots.txt’: No such file or directory
cp: cannot create directory ‘/dist/config’: No such file or directory
cp: cannot create regular file ‘/dist/README.md’: No such file or directory
cp: cannot create directory ‘/dist/_assets’: No such file or directory
cp: cannot create regular file ‘/dist/LICENSE’: No such file or directory
cp: cannot create regular file ‘/dist/package.json’: No such file or directory
cp: cannot create regular file ‘/dist/index.html’: No such file or directory
+ echo 'Generating f8ui integrated planner image from build artifacts...'
Generating f8ui integrated planner image from build artifacts...
```

Also, after the `bootstrap.sh` script completes, I couldn't find any `fabric8-planner-platform` image.

**Comment by debloper** [comment]
Welp... turns out, `echo "This is only needed because the platform build executes `npm run clean`"` ends up executing `npm run clean` (as it should... I'm just dumb to leave it that way, and ignore them in my head "as if" they were comments)

**Comment by fabric8cd** [comment]
@debloper fabric8/fabric8-ui:SNAPSHOT-PR-2309-4 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2309-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@debloper fabric8/fabric8-ui:SNAPSHOT-PR-2309-5 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2309-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@debloper fabric8/fabric8-ui:SNAPSHOT-PR-2309-6 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2309-fabric8-planner.badger.fabric8.io

**Comment by jarifibrahim** [comment]
@debloper Still not working for me. I see 
screenshot from 2017-11-11 15-20-57

and 
```
➜  fabric8-planner git:(deb-2309) ✗ docker run -it --user=root -p 8080:80 --name=fabric8-planner-platform fabric8-planner-platform
2017/11/11 09:50:27 [error] 7#7: *2 directory index of "/usr/share/nginx/html/" is forbidden, client: 172.17.0.1, server: localhost, request: "GET / HTTP/1.1", host: "localhost:8080"
172.17.0.1 - - [11/Nov/2017:09:50:27 +0000] "GET / HTTP/1.1" 403 571 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36" "-"
2017/11/11 09:50:48 [error] 7#7: *2 directory index of "/usr/share/nginx/html/" is forbidden, client: 172.17.0.1, server: localhost, request: "GET / HTTP/1.1", host: "localhost:8080"
172.17.0.1 - - [11/Nov/2017:09:50:48 +0000] "GET / HTTP/1.1" 403 571 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/61.0.3163.100 Safari/537.36" "-"
```

**Comment by jarifibrahim** [comment]
@debloper I see a few errors in the log
```
+ echo 'Linking planner to platform within f8ui build container...'
Linking planner to platform within f8ui build container...
+ docker exec -u root fabric8-ui-builder npm install

> integer@1.0.1 install /home/fabric8/fabric8-ui/node_modules/integer
> node tools/install

make: Entering directory `/home/fabric8/fabric8-ui/node_modules/integer/build'
  CXX(target) Release/obj.target/integer/src/integer.o
make: g++: Command not found
make: *** [Release/obj.target/integer/src/integer.o] Error 127
make: Leaving directory `/home/fabric8/fabric8-ui/node_modules/integer/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.13.5-200.fc26.x86_64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/fabric8/fabric8-ui/node_modules/integer
gyp ERR! node -v v8.3.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 

> farmhash@1.2.1 install /home/fabric8/fabric8-ui/node_modules/farmhash
> node-gyp rebuild

make: Entering directory `/home/fabric8/fabric8-ui/node_modules/farmhash/build'
  CXX(target) Release/obj.target/farmhash-legacy/src/upstream/farmhash-legacy.o
make: g++: Command not found
make: *** [Release/obj.target/farmhash-legacy/src/upstream/farmhash-legacy.o] Error 127
make: Leaving directory `/home/fabric8/fabric8-ui/node_modules/farmhash/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.13.5-200.fc26.x86_64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/fabric8/fabric8-ui/node_modules/farmhash
gyp ERR! node -v v8.3.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 

> better-sqlite3@4.0.3 install /home/fabric8/fabric8-ui/node_modules/better-sqlite3
> node deps/install

==> cwd: /home/fabric8/fabric8-ui/node_modules/better-sqlite3
==> /home/fabric8/fabric8-ui/node_modules/lzz-gyp/lzz-compiled/linux -hx hpp -sx cpp -k BETTER_SQLITE3 -d -hl -sl -e ./src/better_sqlite3.lzz
==> cwd: /home/fabric8/fabric8-ui/node_modules/better-sqlite3
==> node-gyp rebuild
make: Entering directory `/home/fabric8/fabric8-ui/node_modules/better-sqlite3/build'
  ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3190300/sqlite3.c
  TOUCH Release/obj.target/deps/action_before_build.stamp
  CC(target) Release/obj.target/sqlite3/gen/sqlite-autoconf-3190300/sqlite3.o
make: cc: Command not found
make: *** [Release/obj.target/sqlite3/gen/sqlite-autoconf-3190300/sqlite3.o] Error 127
make: Leaving directory `/home/fabric8/fabric8-ui/node_modules/better-sqlite3/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.13.5-200.fc26.x86_64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/fabric8/fabric8-ui/node_modules/better-sqlite3
gyp ERR! node -v v8.3.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
Error: exit code 1
    at ChildProcess.<anonymous> (/home/fabric8/fabric8-ui/node_modules/lzz-gyp/lib/exec.js:19:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)

> phantomjs-prebuilt@2.1.15 install /home/fabric8/fabric8-ui/node_modules/phantomjs-prebuilt
> node install.js

PhantomJS not found on PATH
Downloading https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-linux-x86_64.tar.bz2
Saving to /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
Receiving...

Received 22866K total.
Extracting tar contents (via spawned process)
Removing /home/fabric8/fabric8-ui/node_modules/phantomjs-prebuilt/lib/phantom
Copying extracted folder /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2-extract-1510393221243/phantomjs-2.1.1-linux-x86_64 -> /home/fabric8/fabric8-ui/node_modules/phantomjs-prebuilt/lib/phantom
Writing location.js file
Done. Phantomjs binary available at /home/fabric8/fabric8-ui/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs

> husky@0.14.3 install /home/fabric8/fabric8-ui/node_modules/husky
> node ./bin/install.js

husky
setting up Git hooks
done


> uglifyjs-webpack-plugin@0.4.6 postinstall /home/fabric8/fabric8-ui/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: integer@1.0.1 (node_modules/integer):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: integer@1.0.1 install: `node tools/install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: farmhash@1.2.1 (node_modules/farmhash):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: farmhash@1.2.1 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: better-sqlite3@4.0.3 (node_modules/better-sqlite3):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: better-sqlite3@4.0.3 install: `node deps/install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

added 1894 packages in 495.509s
+ docker exec -u root fabric8-ui-builder npm link /planner
npm ERR! path /planner/package.json
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall open
npm ERR! Error: EACCES: permission denied, open '/planner/package.json'
npm ERR!  { Error: EACCES: permission denied, open '/planner/package.json'
npm ERR!   stack: 'Error: EACCES: permission denied, open \'/planner/package.json\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'open',
npm ERR!   path: '/planner/package.json' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/fabric8/.npm/_logs/2017-11-11T09_40_28_730Z-debug.log
+ echo 'Building platform with integrated planner...'
Building platform with integrated planner..
```

**Comment by debloper** [comment]
@jarifibrahim the node-gyp build failure for farmhash can be ignored (as it's defunct, and fails in CI/CD too - check `build fabric8-ui npm` section's `cd fabric8-ui && npm install` step of any build).

The `EACCES` error seems system specific (I can't reproduce it in my system or in VMs). If I can reliably reproduce it, I should be able to work out a fix, but I suggest you use a fresh system/VM to try it out and see if it happens.

**Comment by fabric8cd** [comment]
@debloper fabric8/fabric8-ui:SNAPSHOT-PR-2309-10 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2309-fabric8-planner.badger.fabric8.io

**Comment by sbose78** [comment]
@pranavgore09 Any way we could follow the same way we handled dev workflow dependencies in WIT, using kedge?

**Comment by pranavgore09** [comment]
> @pranavgore09 Any way we could follow the same way we handled dev workflow dependencies in WIT, using kedge?

Definitely, I am sure that Kedge will help here too.
Noted.

**Comment by jarifibrahim** [comment]
@deb I tried this PR again and it failed.
Here's a part of the log https://paste.fedoraproject.org/paste/biqplVmJiGhVx4KPY8jMBQ

After starting `fabric8-planner-platform` container, I do not get anything on `localhost:80`

**Comment by jarifibrahim** [comment]
Update - The stack works for the dry run with `./scripts/bootstrap.sh --dryrun`.

**Comment by debloper** [comment]
@jarifibrahim thanks, I was going to comment that for this PR we are discounting build related issues causing problems, and as long as the `--dryrun` passes, that's a win for this PR (meaning, the stack is working as intended, whether build is or not).

Please add your approval as a review as one review is required to unblock the PR to get merged.

**Comment by fabric8cd** [comment]
@debloper fabric8/fabric8-ui:SNAPSHOT-PR-2309-11 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2309-fabric8-planner.badger.fabric8.io

**Pull request merged**
