### PR TITLE
fix(list): Open option in kebab menu

### PR DESCRIPTION
**Pull request by vikram-raj**
Fix https://github.com/openshiftio/openshift.io/issues/988

### CODE REVIEW

**Comment by fabric8cd** [comment]
@vikram-raj fabric8/fabric8-ui:SNAPSHOT-PR-2171-1 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2171-fabric8-planner.badger.fabric8.io

**Comment by sanbornsen** [comment]
There are two 'open' in the commit message.

**Comment by fabric8cd** [comment]
@vikram-raj fabric8/fabric8-ui:SNAPSHOT-PR-2171-2 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2171-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@vikram-raj fabric8/fabric8-ui:SNAPSHOT-PR-2171-4 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2171-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@vikram-raj fabric8/fabric8-ui:SNAPSHOT-PR-2171-5 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2171-fabric8-planner.badger.fabric8.io

**Pull request merged**
