### PR TITLE
fix(CI/CD): Run functional tests in chrome headless mode instead of using xvfb

### PR DESCRIPTION
**Pull request by jarifibrahim**
We can now run tests against chrome in headless mode. We no longer need to install xvfb and start a virtual display to run the tests.

This PR depends on https://github.com/fabric8-ui/fabric8-planner/pull/2369

### CODE REVIEW

**Comment by fabric8cd** [comment]
@jarifibrahim fabric8/fabric8-ui:SNAPSHOT-PR-2370-1 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2370-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@jarifibrahim fabric8/fabric8-ui:SNAPSHOT-PR-2370-4 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2370-fabric8-planner.badger.fabric8.io

**Comment by jarifibrahim** [comment]
The `run_functional_tests.sh` script now has support for
- User defined `BASE URL`
- `DIRECT CONNECT`protractor flag
- Using chrome in `HEADLESS_MODE` mode

Also, the local web server for serving planner will be started only if `BASE_URL` is not defined.

To run protractor in [directConnect](https://github.com/angular/protractor/blob/master/docs/server-setup.md#connecting-directly-to-browser-drivers) mode (this is much faster than using selenium server)
`DIRECT_CONNECT=true npm run test:funcsmoke`

To run chrome in `headless` mode for running tests
`HEADLESS_MODE=true npm run test:funcsmoke`

To run tests against an already running planner server, set `BASE_URL`
`BASE_URL=http://localhost:8080 npm run test:funcsmoke`

If none of the above variables are set, then the `npm run test:funcsmoke` script will 
1. Start `selenium server` (this is used for communicating with the browser)
2. Start `planner` locally
3. Run tests against chrome

NOTE - `npm run test:funcsmoke` will fail in an environment where there is no display (eg: CI/CD). Set `HEADLESS_MODE` to run tests in such an environment.

**Comment by pranavgore09** [comment]
nice @jarifibrahim , It will help in isolating npm targets!

**Pull request merged**
