### PR TITLE
fix(quick-add): fix quick add for board view

### PR DESCRIPTION
**Pull request by SMahil**
https://github.com/openshiftio/openshift.io/issues/2209

### CODE REVIEW

**Comment by fabric8cd** [comment]
@SMahil fabric8/fabric8-ui:SNAPSHOT-PR-2436-2 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2436-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@SMahil fabric8/fabric8-ui:SNAPSHOT-PR-2436-3 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2436-fabric8-planner.badger.fabric8.io

**Comment by nimishamukherjee** [comment]
Navigating from list to board for the first time does not set the Scenario context and all the work item types are listed
firsttime

After clicking on any of the other options on the side panel, like Experience, and navigating back will set the context and show the correct list.

secondtime

**Note** : The default URL setting has not been done for Board view.

**Comment by fabric8cd** [comment]
@SMahil fabric8/fabric8-ui:SNAPSHOT-PR-2436-4 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2436-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@SMahil fabric8/fabric8-ui:SNAPSHOT-PR-2436-5 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2436-fabric8-planner.badger.fabric8.io

**Comment by nimishamukherjee** [comment]
I'll merge this PR. Will work on setting default URL for board view in another PR.

**Comment by fabric8cd** [comment]
@SMahil fabric8/fabric8-ui:SNAPSHOT-PR-2436-6 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2436-fabric8-planner.badger.fabric8.io

**Pull request merged**
