### PR TITLE
Remove webpack-dashboard

### PR DESCRIPTION
**Pull request by michaelkleinhenz**
..to speed up compile time.

### CODE REVIEW

**Comment by jarifibrahim** [comment]
@michaelkleinhenz Can we please remove `webpack-dashboard` from `runtime/package.json` also?

**Comment by michaelkleinhenz** [comment]
@jarifibrahim huh? I looked there and it wasn't in there. Will check again.

**Comment by michaelkleinhenz** [comment]
Ok, never mind, found it. Updated the PR.

**Comment by fabric8cd** [comment]
@michaelkleinhenz fabric8/fabric8-ui:SNAPSHOT-PR-2412-4 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2412-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@michaelkleinhenz fabric8/fabric8-ui:SNAPSHOT-PR-2412-8 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2412-fabric8-planner.badger.fabric8.io

**Pull request merged**
