### PR TITLE
fix(test):screen resolution in headless mode

### PR DESCRIPTION
**Pull request by rgarg1**
Changed resolution to 1920x1080x24

### CODE REVIEW

**Comment by debloper** [comment]
Is there any discussion/context requiring this change?
FWIW, 1080p is still not dominant resolution yet; 1366x768 is.

statcounter-resolution-ww-monthly-201609-201709

Otherwise, it looks good to me.

**Comment by rgarg1** [comment]
@debloper Its done to match the resolution set in UI mode as few tests were failing ofetn due to res mismatch. Agree that 1366x768 is the most commonly found resolution though. Any comments @ldimaggi ?

**Comment by fabric8cd** [comment]
@rgarg1 fabric8/fabric8-ui:SNAPSHOT-PR-2182-3 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2182-fabric8-planner.badger.fabric8.io

**Comment by aslakknutsen** [comment]
The design is targeted for 1400x according to @mindreeper2420. Shouldn't the UI Tests reflect that?

**Comment by mindreeper2420** [comment]
The visual design team has set the default to be 1440 x 900, which is what the default screens (when developed) are tested against first. 
Ideally, resolution tests would check against the defaults of PatternFly, as that is our framework.

**Comment by fabric8cd** [comment]
@rgarg1 fabric8/fabric8-ui:SNAPSHOT-PR-2182-5 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2182-fabric8-planner.badger.fabric8.io

**Comment by ldimaggi** [comment]
I would vote for 1440 x 900 for the tests - to match the design.

**Comment by SMahil** [comment]
@mindreeper2420 I f we set resolution 1440 * 900 tests on device-width below than that are failing.
AFAIK 1024px was considered as min targeted device-width. Shouldn't we keep 1024px?

**Comment by mindreeper2420** [comment]
Ideally, the tests would capture all of the resolutions supported by Bootstrap's grid system. As the standard resolution for visual designs is 1440 x 900, the tests, at a minimum, should verify that the site fits the design specs. Nothing from UX is set at 1024 x 768 (mobile).

As far as I am aware, the majority of the site will fail when tested against a 1024x768 resolution. There are Issues in place to address these defects, but they have not been completed at this time.

**Comment by rgarg1** [comment]
Updated the test resolution to 1440x900 as suggested.

**Comment by rgarg1** [comment]
Updated a few tests as they were failing, but only in CI. All tests PASS locally.

**Comment by fabric8cd** [comment]
@rgarg1 fabric8/fabric8-ui:SNAPSHOT-PR-2182-12 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2182-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@rgarg1 fabric8/fabric8-ui:SNAPSHOT-PR-2182-13 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2182-fabric8-planner.badger.fabric8.io

**Pull request merged**
