### PR TITLE
WIP - Migrate UI Tests to run against the new DB

### PR DESCRIPTION
**Pull request by jarifibrahim**
This PR depends on https://github.com/fabric8-ui/ngx-login-client/pull/96

Update - 
This PR updates smoke tests and UI functional tests to run against the DB generated by `EE_API_automation` tests and the current `inmemory` mode (see constants.js file)

To run tests against the new DB, following variables have to set
- `SPACE_NAME` - The name of space that contains the workitems
- `USER` - Username of the user
- `FULL_NAME` - Full name of the user
- `AUTH_TOKEN` and `REFRESH_TOKEN` - For login purpose

To run against local minishift setup-
`SPACE_NAME="---" USER="--" FULL_NAME="--" AUTH_TOKEN="--" REFRESH_TOKEN="--" $(npm bin)/protractor protractor.config.js --baseUrl="http://minishift.local:31200" --suite smokeTest`

### CODE REVIEW

**Comment by rgarg1** [comment]
Testing this PR depends upon merging of: https://github.com/fabric8-ui/ngx-login-client/pull/96

**Comment by fabric8cd** [comment]
@jarifibrahim fabric8/fabric8-ui:SNAPSHOT-PR-2356-6 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2356-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@jarifibrahim fabric8/fabric8-ui:SNAPSHOT-PR-2356-11 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2356-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@jarifibrahim fabric8/fabric8-ui:SNAPSHOT-PR-2356-12 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2356-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@jarifibrahim fabric8/fabric8-ui:SNAPSHOT-PR-2356-21 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2356-fabric8-planner.badger.fabric8.io

**Comment by jarifibrahim** [comment]
Closing this PR since we'll be using Typescript based tests https://github.com/fabric8-ui/fabric8-planner/pull/2417 which makes this PR obsolete.

**Pull request closed without merging**
