### PR TITLE
fix(quickAdd): Quick-add drop-down menu grays out if a filter is applied

### PR DESCRIPTION
**Pull request by sahil143**
fix OSIO: [1794](https://openshift.io/openshiftio/openshiftio/plan/detail/1794)
screen shot 2018-01-29 at 6 37 11 pm

### CODE REVIEW

**Comment by fabric8cd** [comment]
@sahil143 fabric8/fabric8-ui:SNAPSHOT-PR-2422-4 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2422-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@sahil143 fabric8/fabric8-ui:SNAPSHOT-PR-2422-5 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2422-fabric8-planner.badger.fabric8.io

**Comment by sahil143** [comment]
@nimishamukherjee task to track Unit Tests https://openshift.io/openshiftio/openshiftio/plan/detail/1859

**Comment by fabric8cd** [comment]
@sahil143 fabric8/fabric8-ui:SNAPSHOT-PR-2422-8 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2422-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@sahil143 fabric8/fabric8-ui:SNAPSHOT-PR-2422-14 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2422-fabric8-planner.badger.fabric8.io

**Pull request merged**
