### PR TITLE
fix(filters): don't filter out the only element in a single-element query list

### PR DESCRIPTION
**Pull request by debloper**
Closes openshiftio/openshift.io#1983

~~Blocked by #2441~~

### CODE REVIEW

**Comment by fabric8cd** [comment]
@debloper fabric8/fabric8-ui:SNAPSHOT-PR-2480-1 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2480-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@debloper fabric8/fabric8-ui:SNAPSHOT-PR-2480-2 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2480-fabric8-planner.badger.fabric8.io

**Comment by sanbornsen** [comment]
This issue is fixed in the new version. 

Try out - http://fabric8-ui-fabric8-planner.badger.fabric8.io/

@debloper please verify and close the PR.

**Comment by debloper** [comment]
Seems to be working on the [badger instance](http://fabric8-ui-fabric8-planner.badger.fabric8.io/)

**Comment by fabric8cd** [comment]
@debloper fabric8/fabric8-ui:SNAPSHOT-PR-2480-3 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2480-fabric8-planner.badger.fabric8.io

**Pull request closed without merging**
