### PR TITLE
fix(labels): User experience bugs fixed

### PR DESCRIPTION
**Pull request by sanbornsen**
- Save labels on close selector dropdown
- Show loading while resolvong or saving labels

### CODE REVIEW

**Comment by fabric8cd** [comment]
@sanbornsen fabric8/fabric8-ui:SNAPSHOT-PR-2158-3 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2158-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@sanbornsen fabric8/fabric8-ui:SNAPSHOT-PR-2158-4 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2158-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@sanbornsen fabric8/fabric8-ui:SNAPSHOT-PR-2158-5 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2158-fabric8-planner.badger.fabric8.io

**Comment by sanbornsen** [comment]
@nimishamukherjee all the problems you identified are resolved here - https://github.com/fabric8-ui/fabric8-planner/pull/2168

Even though they are not label related problems but since we figured them out with labels let's keep it all together. Hence I am closing this PR.

**Pull request closed without merging**
