### PR TITLE
fix(test): Fix edit/cancel comment test

### PR DESCRIPTION
**Pull request by jarifibrahim**
This PR fixes the failing edit/cancel comment smoke test. @sanbornsen Please review.

### CODE REVIEW

**Comment by fabric8cd** [comment]
@jarifibrahim fabric8/fabric8-ui:SNAPSHOT-PR-2162-1 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2162-fabric8-planner.badger.fabric8.io

**Comment by rgarg1** [comment]
Failing in CI due to could not connect to jenkins-slave.

**Comment by fabric8cd** [comment]
@jarifibrahim fabric8/fabric8-ui:SNAPSHOT-PR-2162-3 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2162-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@jarifibrahim fabric8/fabric8-ui:SNAPSHOT-PR-2162-4 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2162-fabric8-planner.badger.fabric8.io

**Pull request merged**
