### PR TITLE
fix(inlineinput): WI title submits on enter

### PR DESCRIPTION
**Pull request by divyanshiGupta**

### CODE REVIEW

**Comment by fabric8cd** [comment]
@divyanshiGupta fabric8/fabric8-ui:SNAPSHOT-PR-2430-1 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2430-fabric8-planner.badger.fabric8.io

**Comment by rgarg1** [comment]
@divyanshiGupta LGTM. Why can't the inline-add box stay open after a workitem is added. Auto-close is going to make it difficult for users to add multiple children.

**Comment by divyanshiGupta** [comment]
@rgarg the aim here is to replicate the action performed on clicking the submit button right next to the text area, on pressing enter. Here this inlineinput component is being used just to update the title of the WI.

**Comment by divyanshiGupta** [comment]
@rgarg1 please refer this https://github.com/openshiftio/openshift.io/issues/1992#issuecomment-362239452

**Comment by rgarg1** [comment]
@divyanshiGupta That does not answers my question. I'll try again.

So is it a component limitation that the user needs to reopen the inline-add dialog every time a new child workitem is added?

**Comment by divyanshiGupta** [comment]
@rgarg1 you mean that the text area should always be editable even after submitting?

**Comment by rgarg1** [comment]
Yes. To allow addition of more workitems. Once the user is done, he can choose to explicitly close the UI.

**Comment by divyanshiGupta** [comment]
@rgarg1 can you add screenshots or a gif so that I can understand clearly what exactly you are talking about.

**Comment by divyanshiGupta** [comment]
@rgarg1 that can be done but I think this is not a part of this bug and I think we need to talk to @michaelkleinhenz about this as we are talking about changing the current behavior.

**Comment by rgarg1** [comment]
Agreed @divyanshiGupta . My intention was not to block this PR, but asking to understand the limitations to get it done.

The feature I'm talking about  has been discussed many times in the past, but I'm not aware what is stopping us.

**Comment by divyanshiGupta** [comment]
@rgarg1 what you are suggesting can be done but we need more clarity. We can discuss this in cabal. Or after all of you are back in Bangalore.

**Comment by jarifibrahim** [comment]
@rgarg1 

> So is it a component limitation that the user needs to reopen the inline-add dialog every time a new child workitem is added?

No. We explicitly close the inline-quickadd after the child is created. 
https://github.com/fabric8-ui/fabric8-planner/blob/b4fb10f957f23d6063b8775d472ebfacae6798e8/src/app/components/planner-list/planner-list.component.ts#L808

**Comment by nimishamukherjee** [comment]
@rgarg1 the component, InlineInputModule, @divyanshiGupta has modified is used only in the work item detail page. 
Please create a new issue for the child inline add component and assign it to @sahil143

**Comment by rgarg1** [comment]
@divyanshiGupta @nimishamukherjee @sahil143 Here is the bug:
https://openshift.io/openshiftio/openshiftio/plan/detail/1882

**Comment by fabric8cd** [comment]
@divyanshiGupta fabric8/fabric8-ui:SNAPSHOT-PR-2430-3 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2430-fabric8-planner.badger.fabric8.io

**Comment by divyanshiGupta** [comment]
@nimishamukherjee can we merge this?

**Comment by fabric8cd** [comment]
@divyanshiGupta fabric8/fabric8-ui:SNAPSHOT-PR-2430-5 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2430-fabric8-planner.badger.fabric8.io

**Comment by rgarg1** [comment]
Approved!

**Pull request merged**
