### PR TITLE
fix(list-view): align list view to top

### PR DESCRIPTION
**Pull request by SMahil**
Align list view to top

### CODE REVIEW

**Comment by fabric8cd** [comment]
@SMahil fabric8/fabric8-ui:SNAPSHOT-PR-2344-2 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2344-fabric8-planner.badger.fabric8.io

**Comment by jarifibrahim** [comment]
@nimishamukherjee @SMahil Is there an issue this?

**Comment by jarifibrahim** [comment]
@SMahil The `>` and title are not in alignment
download 5

**Comment by fabric8cd** [comment]
@SMahil fabric8/fabric8-ui:SNAPSHOT-PR-2344-3 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2344-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@SMahil fabric8/fabric8-ui:SNAPSHOT-PR-2344-4 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2344-fabric8-planner.badger.fabric8.io

**Pull request merged**
