### PR TITLE
fix(filter): fixed filtering un-assigned work items

### PR DESCRIPTION
**Pull request by sanbornsen**
This PR fixes following issue 
https://github.com/openshiftio/openshift.io/issues/2448

### CODE REVIEW

**Comment by rgarg1** [comment]
@sanbornsen Tests please :)

**Comment by fabric8cd** [comment]
@sanbornsen fabric8/fabric8-ui:SNAPSHOT-PR-2495-2 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2495-fabric8-planner.badger.fabric8.io

**Comment by Raunak1203** [comment]
screenshot from 2018-03-13 11-03-52

**Comment by alien-ike** [comment]
### Ike Plugins (test-keeper)

Thank you @sanbornsen for this contribution!



It appears that no tests have been added or updated in this PR.

Automated tests give us confidence in shipping reliable software. Please add some as part of this change.

If you are an admin and you are sure that no test is needed then you can use the command `/ok-without-tests` as a comment to make the status green.


For more information please head over to official [documentation](http://arquillian.org/ike-prow-plugins/#_test_keeper_plugin). You can find there how to configure the plugin - for example exclude certain file types so if PR contains only them it won't be checked.

**Comment by Raunak1203** [comment]
Here is the test for the PR: https://github.com/fabric8-ui/fabric8-planner/pull/2627

**Pull request merged**
