### PR TITLE
WIP testing builder image change

### PR DESCRIPTION
**Pull request by pranavgore09**
testing https://github.com/fabric8io-images/fabric8-ui-builder/pull/6 and https://github.com/fabric8io/fabric8-pipeline-library/pull/375

### CODE REVIEW

**Comment by jarifibrahim** [comment]
@pranavgore09 Looks great. I do not see those `missing gcc/g++` errors.

On a side note, we might not need gcc/g++ after this https://github.com/fabric8-ui/fabric8-planner/pull/2412 is merged. The gcc/g++ is required by the dependencies (integer, farmhash, better-sqlite) of `webpack-dashboard`.

**Comment by fabric8cd** [comment]
@pranavgore09 fabric8/fabric8-ui:SNAPSHOT-PR-2418-3 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2418-fabric8-planner.badger.fabric8.io

**Comment by pranavgore09** [comment]
@michaelkleinhenz this PR gets rid of `g++ command not found` errors in build, but as this comment says https://github.com/fabric8-ui/fabric8-planner/pull/2418#issuecomment-360518873 we may not need this change, can you please confirm?

**Comment by jarifibrahim** [comment]
Closing this PR since we no longer have the `missing g++` error.

**Pull request closed without merging**
