### PR TITLE
fix(test): Add add/update iteration modal tests

### PR DESCRIPTION
**Pull request by jarifibrahim**

### CODE REVIEW

**Comment by jarifibrahim** [comment]
Test result log - https://pastebin.com/WaKRDKf9

Few tests are still failing. I'll send a seperate PR for those.

**Comment by jarifibrahim** [comment]
All tests have been fixed and pass successfully.

Updated test result log - https://pastebin.com/Sym4bq2d

**Comment by fabric8cd** [comment]
@jarifibrahim fabric8/fabric8-ui:SNAPSHOT-PR-2157-5 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2157-fabric8-planner.badger.fabric8.io

**Comment by rgarg1** [comment]
Way to go @jarifibrahim

**Comment by fabric8cd** [comment]
@jarifibrahim fabric8/fabric8-ui:SNAPSHOT-PR-2157-6 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2157-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@jarifibrahim fabric8/fabric8-ui:SNAPSHOT-PR-2157-7 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2157-fabric8-planner.badger.fabric8.io

**Pull request merged**
