### PR TITLE
fix(link): work item can not be self linked.

### PR DESCRIPTION
**Pull request by vikram-raj**
### [ ] What does this PR do? _[Mandatory]_
_Note: If you are still working on the changes, prefix the PR title with "WIP" and add the label "DO NOT MERGE"_

 - A work item cannot be self linked.

### [ ] What issue/task does this PR references? _[Mandatory]_

https://github.com/openshiftio/openshift.io/issues/3205

### [ ] Are the tests Included? _[Mandatory]_

No

### CODE REVIEW

**Comment by alien-ike** [comment]
### Ike Plugins (test-keeper)

Thank you @vikram-raj for this contribution!



It appears that no tests have been added or updated in this PR.

Automated tests give us confidence in shipping reliable software. Please add some as part of this change.

If you are an admin or the reviewer of this PR and you are sure that no test is needed then you can use the command `/ok-without-tests` as a comment to make the status green.


Your plugin configuration is stored in the [file](https://github.com/fabric8-ui/fabric8-planner/b2cbd3a342c8351bd6f287ab8db4770d2e12720a/test-keeper.yml).

**Comment by vikram-raj** [comment]
> It works if I open and close quick Preview but If I've Quick Preview already open and switch to other workitem then workItem can be self linked. Could you please check

@Raunak1203 Fixed.

**Comment by nimishamukherjee** [comment]
[test]

**Comment by jarifibrahim** [comment]
[test]

**Pull request merged**
