### PR TITLE
fix(stylelint): add stylelint to build process

### PR DESCRIPTION
**Pull request by mindreeper2420**
Add Stylelint to the build process, with warnings and errors displayed as necessary

Build process configured so that it does not fail on error, but will display all errors and/or warnings in the console.

closes https://github.com/fabric8-ui/fabric8-planner/issues/2147

### CODE REVIEW

**Comment by fabric8cd** [comment]
@mindreeper2420 fabric8/fabric8-ui:SNAPSHOT-PR-2150-1 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2150-fabric8-planner.badger.fabric8.io

**Comment by mindreeper2420** [comment]
As part of this PR, there are various methods for running Stylelint:

1) As part of the build - either by using `npm run build:library` or `npm run watch:library`.
    - watching will re-lint, transpile and handle updated `.less` files
    - errors will be printed out in the string format, with file that errors appears on, as well as what the error is
2) As a Node script - `npm run stylelint`.
    - This will run the `gulp stylelint` task, which outputs errors in a verbose format, giving an outline of the total number errors, warnings and of each type.
3) As a Gulp task - `gulp lint-less`
    - This will run only the gulp task that lints the `.less` files. This is one of the various parts that may up the `build:library` script, but is a quick way to check the `.less` files, without installing Stylelint globally and running commands through it's CLI.

**Comment by joshuawilson** [comment]
[test]

**Comment by michaelkleinhenz** [comment]
@mindreeper2420 can you add that documentation to the readme?

**Comment by mindreeper2420** [comment]
@michaelkleinhenz Readme has been updated, as well as the Building Planner doc to reference Less, rather than Sass.

**Comment by mindreeper2420** [comment]
@michaelkleinhenz @SMahil Of note - currently, the Gulp task is set to not fail the build on any errors. Ideally, this would change once the files are cleaned to match the Stylelint configuration criteria.

**Current**
```
  .pipe(gulpStylelint({
    failAfterError: false,
    reporters: [{
      formatter: 'string', console: true
    }]
  }));
```

**Should Be**
```
  .pipe(gulpStylelint({
    failAfterError: true,
    reporters: [{
      formatter: 'string', console: true
    }]
  }));
```

**Comment by mindreeper2420** [comment]
@michaelkleinhenz documentation updated to reflect what was written here. Regarding holding off on merging, there shouldn't be a risk with merging this - the sooner it is in, the quicker fixes can be applied to areas that could potential be causing issues in the current production environment (conflicts with Platform, overwrites, etc).

Regarding builds, it should not fail any builds, so it can be merged without causing errors - it will just print warnings in the console at build time.

**Comment by michaelkleinhenz** [comment]
Ok, approved.

**Comment by joshuawilson** [comment]
I re-triggered the build.

**Comment by fabric8cd** [comment]
@mindreeper2420 fabric8/fabric8-ui:SNAPSHOT-PR-2150-2 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2150-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@mindreeper2420 fabric8/fabric8-ui:SNAPSHOT-PR-2150-4 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2150-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@mindreeper2420 fabric8/fabric8-ui:SNAPSHOT-PR-2150-7 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2150-fabric8-planner.badger.fabric8.io

**Comment by mindreeper2420** [comment]
Since this has been open for over a month without a resolution (after two approvals), I'm going to close this and let someone else pick up the work.

**Comment by joshuawilson** [comment]
Can you please just rebase it and I'll merge it.

**Comment by mindreeper2420** [comment]
@joshuawilson rebased, but there is a build error. It exists on Master as well ("error in plugin gulp-ngc").

**Comment by joshuawilson** [comment]
@mindreeper2420 so @michaelkleinhenz and I were working on it, once that is resolved we can just rerun the build check.

**Comment by mindreeper2420** [comment]
@joshuawilson @michaelkleinhenz thoughts on this? I believe this is the last repo to have stylelint enabled. I can update the branch again, if needed.

**Comment by joshuawilson** [comment]
@mindreeper2420 I do believe @michaelkleinhenz and I got the build and versions sorted out. Please rebase and let's see what happens.

**Comment by mindreeper2420** [comment]
@nimishamukherjee I've rebased and checked the new processes. Everything appears to be working as expected.

**Comment by mindreeper2420** [comment]
Updated with latest Master.

**Comment by joshuawilson** [comment]
Are you going to make a new PR @mindreeper2420 

@michaelkleinhenz it would have been really good to get this merged

**Comment by mindreeper2420** [comment]
@joshuawilson new PR is #2372. The build is failing on that PR as well.

**Comment by joshuawilson** [comment]
thanks

**Pull request closed without merging**
