### PR TITLE
fix(side-panel): fix side panel alignment issues

### PR DESCRIPTION
**Pull request by SMahil**
This PR consists of issues in sidepanel as per UX review

Link to the issue: https://redhat.invisionapp.com/share/NCDYS7ZY7#/screens/258475883

### CODE REVIEW

**Comment by rgarg1** [comment]
waiting on the preview to be available.

**Comment by fabric8cd** [comment]
@SMahil fabric8/fabric8-ui:SNAPSHOT-PR-2280-2 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2280-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@SMahil fabric8/fabric8-ui:SNAPSHOT-PR-2280-3 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2280-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@SMahil fabric8/fabric8-ui:SNAPSHOT-PR-2280-4 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2280-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@SMahil fabric8/fabric8-ui:SNAPSHOT-PR-2280-5 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2280-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@SMahil fabric8/fabric8-ui:SNAPSHOT-PR-2280-6 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2280-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@SMahil fabric8/fabric8-ui:SNAPSHOT-PR-2280-7 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2280-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@SMahil fabric8/fabric8-ui:SNAPSHOT-PR-2280-8 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2280-fabric8-planner.badger.fabric8.io

**Comment by rgarg1** [comment]
Looks good to QE, however I'd recommend a UX signoff.

**Comment by fabric8cd** [comment]
@SMahil fabric8/fabric8-ui:SNAPSHOT-PR-2280-9 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2280-fabric8-planner.badger.fabric8.io

**Comment by sunilmalagi** [comment]
@SMahil  @nimishamukherjee Sorry I am not able to review the page as I am getting this message: 
"{"errors":[{"code":"unauthorized_error","detail":"user 'smalagi' is not approved","status":"401","title":"Unauthorized error"}]}"

**Comment by fabric8cd** [comment]
@SMahil fabric8/fabric8-ui:SNAPSHOT-PR-2280-10 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2280-fabric8-planner.badger.fabric8.io

**Comment by nimishamukherjee** [comment]
Functional tests pass locally.

**Comment by rgarg1** [comment]
@sunilmalagi You should be able to review now. Could you please signoff. Thanks.

**Comment by fabric8cd** [comment]
@SMahil fabric8/fabric8-ui:SNAPSHOT-PR-2280-14 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2280-fabric8-planner.badger.fabric8.io

**Comment by sunilmalagi** [comment]
@SMahil please look at the jump when you expand the side panel.

**Comment by jarifibrahim** [comment]
The tests on CI are failing as the tests do not wait for the element to be rendered. https://github.com/fabric8-ui/fabric8-planner/pull/2327 fixes this issue.

**Comment by fabric8cd** [comment]
@SMahil fabric8/fabric8-ui:SNAPSHOT-PR-2280-19 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2280-fabric8-planner.badger.fabric8.io

**Pull request merged**
