### PR TITLE
fix(datatable): remove last column

### PR DESCRIPTION
**Pull request by sahil143**
### [ ] What does this PR do? _[Mandatory]_
Remove the last column from datatable

### [ ] What issue/task does this PR references? _[Mandatory]_

https://github.com/openshiftio/openshift.io/issues/2602

### [ ] Are the tests Included? _[Mandatory]_

NA

### CODE REVIEW

**Comment by jarifibrahim** [comment]
[test]

**Comment by Raunak1203** [comment]
@sahil143 please fix "Work Item datatable list should open settings button and hide columns" test in workItemTableTestSpec.ts...This tests expects 10 column, but now it should be updated

**Comment by nimishamukherjee** [comment]
[test]

**Comment by nimishamukherjee** [comment]
@Raunak1203 can you do a hard refresh and see if you face the issue?

**Comment by nimishamukherjee** [comment]
[test]

**Pull request merged**
