### PR TITLE
fix(listview): Adds context to new work item create flow. Fixes #279.

### LINKED ISSUE #279: Active State Identifiers
According to the Visual Design, the active state of an input should be represented by a light blue border with light blue shadowing. Currently, there is an inconsistency between the Title and Description regarding this visual.

* Visual Design for Title
item details - update 2x

* Visual Design for Description
a-0500-description_-_hover

* [PatternFly form input design guidelines](http://www.patternfly.org/pattern-library/forms-and-controls/forms/#_design)

Title input has no highlighting:
screen shot 2016-11-08 at 10 06 14 am

Description input only has dark blue outline:
screen shot 2016-11-08 at 10 06 21 am

### PR DESCRIPTION
**Pull request by michaelkleinhenz**
This adds context to the new WI flow. Adding a new work item from the toolbar or the empty list now has iteration and area preselected.

### CODE REVIEW

**Comment by fabric8cd** [comment]
@michaelkleinhenz fabric8/fabric8-ui:SNAPSHOT-PR-2188-2 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2188-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@michaelkleinhenz fabric8/fabric8-ui:SNAPSHOT-PR-2188-5 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2188-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@michaelkleinhenz fabric8/fabric8-ui:SNAPSHOT-PR-2188-6 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2188-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@michaelkleinhenz fabric8/fabric8-ui:SNAPSHOT-PR-2188-7 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2188-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@michaelkleinhenz fabric8/fabric8-ui:SNAPSHOT-PR-2188-9 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2188-fabric8-planner.badger.fabric8.io

**Comment by michaelkleinhenz** [comment]
@nimishamukherjee this is not currently supported, due to the area not part of the query parameter. If we add the area to the q param, this should work out-of-the-box.

**Comment by fabric8cd** [comment]
@michaelkleinhenz fabric8/fabric8-ui:SNAPSHOT-PR-2188-11 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2188-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@michaelkleinhenz fabric8/fabric8-ui:SNAPSHOT-PR-2188-13 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2188-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@michaelkleinhenz fabric8/fabric8-ui:SNAPSHOT-PR-2188-15 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2188-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@michaelkleinhenz fabric8/fabric8-ui:SNAPSHOT-PR-2188-16 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2188-fabric8-planner.badger.fabric8.io

**Pull request merged**
