### PR TITLE
fix(tests) Run functests using missing commands

### PR DESCRIPTION
**Pull request by hectorj2f**

### CODE REVIEW

**Comment by hectorj2f** [comment]
[test]

**Comment by hectorj2f** [comment]
[test]

**Comment by hectorj2f** [comment]
[test]

**Comment by fabric8cd** [comment]
@hectorj2f snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2003-fabric8-planner.int.rdu2c.fabric8.io

**Comment by hectorj2f** [comment]
[test]

**Comment by hectorj2f** [comment]
related to https://github.com/fabric8io/fabric8-planner/issues/2016

**Comment by hectorj2f** [comment]
I am running a dummy test that use our headless chrome image. It works without any problem. So I would say the tests aren't working due to an unknown reason.

conf.js
```
exports.config = {
  seleniumAddress: 'http://localhost:4444/wd/hub',
  specs: ['todo-spec.js'],
    capabilities: {
      'browserName': 'chrome',
      'maxInstances': 2,
      'shardTestFiles': true,
      'loggingPrefs': {
      'driver': 'WARNING',
      'server': 'WARNING',
      'browser': 'INFO'
      },
      'chromeOptions': {
      'args': [ '--no-sandbox']
      }
    }

};
```
and using the spec
```
ddescribe('angularjs homepage todo list', function() {
  it('should add a todo', function() {
    browser.get('https://angularjs.org');

    element(by.model('todoList.todoText')).sendKeys('write first protractor test');
    element(by.css('[value="add"]')).click();

    var todoList = element.all(by.repeater('todo in todoList.todos'));
    expect(todoList.count()).toEqual(3);
    expect(todoList.get(2).getText()).toEqual('write first protractor test');

    // You wrote your first test, cross it off the list
    todoList.get(2).element(by.css('input')).click();
    var completedAmount = element.all(by.css('.done-true'));
    expect(completedAmount.count()).toEqual(2);
  });
});
```

**Comment by fabric8cd** [comment]
@hectorj2f snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2003-fabric8-planner.badger.fabric8.io

**Pull request merged**
