### PR TITLE
Filter by title 

### PR DESCRIPTION
**Pull request by vikram-raj**
Query language is yet to support filter by title.

### CODE REVIEW

**Comment by fabric8cd** [comment]
@vikram-raj fabric8/fabric8-ui:SNAPSHOT-PR-2273-2 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2273-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@vikram-raj fabric8/fabric8-ui:SNAPSHOT-PR-2273-6 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2273-fabric8-planner.badger.fabric8.io

**Comment by sanbornsen** [comment]
@jarifibrahim good find. Any string with "(" and ")" will fail and I know is it happening. The algorithm which converts the query to JSON doesn't respect brackets in value.

**Comment by sanbornsen** [comment]
Let this PR go in because it's a very important feature. The issue pointed is not related to this PR directly and will be fixed soon. I take it up.

**Comment by vikram-raj** [comment]
@jarifibrahim Created issue for support brackets in work item title filter. https://openshift.io/openshiftio/openshiftio/plan/detail/1714

**Comment by fabric8cd** [comment]
@vikram-raj fabric8/fabric8-ui:SNAPSHOT-PR-2273-7 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2273-fabric8-planner.badger.fabric8.io

**Pull request merged**
