### PR TITLE
Show/hide work items in the list if it matches the current applied filters after an update.

### PR DESCRIPTION
**Pull request by nimishamukherjee**
Fixes https://openshift.io/openshiftio/openshiftio/plan/detail/1542

### CODE REVIEW

**Comment by fabric8cd** [comment]
@nimishamukherjee fabric8/fabric8-ui:SNAPSHOT-PR-2278-2 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2278-fabric8-planner.badger.fabric8.io

**Comment by rgarg1** [comment]
The behavior appear fixed now as the workitem move to the new iteration context immediately.

**Comment by fabric8cd** [comment]
@nimishamukherjee fabric8/fabric8-ui:SNAPSHOT-PR-2278-3 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2278-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@nimishamukherjee fabric8/fabric8-ui:SNAPSHOT-PR-2278-4 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2278-fabric8-planner.badger.fabric8.io

**Pull request merged**
