### PR TITLE
fix(tests) : Add tests for Board view

### PR DESCRIPTION
**Pull request by Raunak1203**
<strong>Note: If there are pending changes to the PR, prefix the PR title with "WIP" and add the label "DO NOT MERGE"</strong>

### Mandatory
 - [ ] What does this PR do? 

- [ ] What issue/task does this PR references?

- [ ] Are the tests Included?
___
### Optional
- [ ] Is the documentation Included?

- [ ] Are the Release Notes included?

- [ ] @mention(s) to expected reviewer(s) included

### CODE REVIEW

**Comment by Raunak1203** [comment]
[test]

**Comment by Raunak1203** [comment]
[test]

**Comment by Raunak1203** [comment]
[test]

**Comment by joshuawilson** [comment]
@Raunak1203 can you please rebase this and get it to a state that it can be merged?

**Comment by Raunak1203** [comment]
Since we are no longer working on board view. So, this PR is irrelevant and Hence closing this PR.
cc @michaelkleinhenz

**Pull request closed without merging**
