### PR TITLE
Filter query basic implementation

### PR DESCRIPTION
**Pull request by sanbornsen**

### CODE REVIEW

**Comment by fabric8cd** [comment]
@sanbornsen fabric8/fabric8-ui:SNAPSHOT-PR-2076-2 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2076-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@sanbornsen fabric8/fabric8-ui:SNAPSHOT-PR-2076-3 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2076-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@sanbornsen fabric8/fabric8-ui:SNAPSHOT-PR-2076-4 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2076-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@sanbornsen fabric8/fabric8-ui:SNAPSHOT-PR-2076-5 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2076-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@sanbornsen fabric8/fabric8-ui:SNAPSHOT-PR-2076-6 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2076-fabric8-planner.badger.fabric8.io

**Comment by sanbornsen** [comment]
@nimishamukherjee you'll have to change the view from hierarchy to flat. Core doesn't support **parentexist=true** yet. @baijum is working on it.

**Comment by fabric8cd** [comment]
@sanbornsen fabric8/fabric8-ui:SNAPSHOT-PR-2076-8 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2076-fabric8-planner.badger.fabric8.io

**Comment by nimishamukherjee** [comment]
@sanbornsen we will merge the PR after the backend fix is in.

**Comment by fabric8cd** [comment]
@sanbornsen fabric8/fabric8-ui:SNAPSHOT-PR-2076-9 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2076-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@sanbornsen fabric8/fabric8-ui:SNAPSHOT-PR-2076-12 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2076-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@sanbornsen fabric8/fabric8-ui:SNAPSHOT-PR-2076-13 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2076-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@sanbornsen fabric8/fabric8-ui:SNAPSHOT-PR-2076-16 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2076-fabric8-planner.badger.fabric8.io

**Comment by rgargosiotest1** [comment]
The filters are not working yet. Is it due to a dependency?

**Comment by fabric8cd** [comment]
@sanbornsen fabric8/fabric8-ui:SNAPSHOT-PR-2076-17 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2076-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@sanbornsen fabric8/fabric8-ui:SNAPSHOT-PR-2076-18 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2076-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@sanbornsen fabric8/fabric8-ui:SNAPSHOT-PR-2076-19 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2076-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@sanbornsen fabric8/fabric8-ui:SNAPSHOT-PR-2076-21 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2076-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@sanbornsen fabric8/fabric8-ui:SNAPSHOT-PR-2076-22 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2076-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@sanbornsen fabric8/fabric8-ui:SNAPSHOT-PR-2076-23 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2076-fabric8-planner.badger.fabric8.io

**Pull request merged**
