### PR TITLE
NGRX version bug fixes

### PR DESCRIPTION
**Pull request by sanbornsen**
This PR includes following bug fixes and updates 

- Quick preview component was removed, as both of non-contextual detail page and the quick preview is being served from one component.
- The list page is updated with better store observable handling.
- Loaders added to the side panel.
- Space change handled with some level of architectural updates
  - All the Get actions of the attributes like iteration, area etc (space
dependent attributes) are moved from components to space effect.
  - On Get space success we trigger the Get actions of all these
attributes. Components are only listening for them and triggering the
Get action for space and wor items
- Duplicate children bug fixed
- List refresh bug on adding iteration or label bug fixed (https://github.com/openshiftio/openshift.io/issues/2468)

### CODE REVIEW

**Comment by fabric8cd** [comment]
@sanbornsen fabric8/fabric8-ui:SNAPSHOT-PR-2488-10 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2488-fabric8-planner.badger.fabric8.io

**Comment by rgarg1** [comment]
All 3 issues addressed by this PR have been validated as fixed. 

Requesting to add tests to this PR and then we can merge it.

**Comment by sanbornsen** [comment]
The tests are added to the following PR
https://github.com/fabric8-ui/fabric8-planner/pull/2490

Reference commits are - 
4eb99a822b9eba0fccff3f31e88aa9ea6b3e8866
083372a1b3ba7087d492056e9194b563ff8a7f29

**Comment by rgarg1** [comment]
Approved @sanbornsen. Good work with the functional tests.

Kindly add a story to the Planner backlog as we discussed, to enable effective Unit Testing. This would an engineering backlog item. @michaelkleinhenz @nimishamukherjee

**Comment by fabric8cd** [comment]
@sanbornsen fabric8/fabric8-ui:SNAPSHOT-PR-2488-12 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2488-fabric8-planner.badger.fabric8.io

**Pull request merged**
