### PR TITLE
All filters in board view are fixed

### PR DESCRIPTION
**Pull request by sanbornsen**

### CODE REVIEW

**Comment by fabric8cd** [comment]
@sanbornsen fabric8/fabric8-ui:SNAPSHOT-PR-2282-1 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2282-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@sanbornsen fabric8/fabric8-ui:SNAPSHOT-PR-2282-3 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2282-fabric8-planner.badger.fabric8.io

**Comment by jarifibrahim** [comment]
@sanbornsen Can you please tag the issue this PR fixes?

**Comment by fabric8cd** [comment]
@sanbornsen fabric8/fabric8-ui:SNAPSHOT-PR-2282-4 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2282-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@sanbornsen fabric8/fabric8-ui:SNAPSHOT-PR-2282-5 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2282-fabric8-planner.badger.fabric8.io

**Comment by nimishamukherjee** [comment]
@jarifibrahim this PR fixes
https://openshift.io/openshiftio/openshiftio/plan/detail/1561
https://openshift.io/openshiftio/openshiftio/plan/detail/1563

**Comment by rgarg1** [comment]
@nimishamukherjee @sanbornsen Does this PR also fixes:
1) https://openshift.io/openshiftio/openshiftio/plan/detail/1594
2) https://openshift.io/openshiftio/openshiftio/plan/detail/1595

@sanbornsen said he'll address them as part of this PR itself.

**Comment by jarifibrahim** [comment]
@sanbornsen @nimishamukherjee @rgarg1 Looks like 
https://openshift.io/openshiftio/openshiftio/plan/detail/1561
https://openshift.io/openshiftio/openshiftio/plan/detail/1563
https://openshift.io/openshiftio/openshiftio/plan/detail/1567
https://openshift.io/openshiftio/openshiftio/plan/detail/1594
have been fixed.


https://openshift.io/openshiftio/openshiftio/plan/detail/1595 does not appear to be fixed in this PR. The workitems added via quick-add in board view still vanish in requirements/iteration/portfolio context. The filters should be triggered after creating a workitem which doesn't appear to be working.

**Comment by sanbornsen** [comment]
https://openshift.io/openshiftio/openshiftio/plan/detail/1595

**Comment by nimishamukherjee** [comment]
So I will merge this PR and @sanbornsen will raise another PR for 1595.

**Comment by fabric8cd** [comment]
@sanbornsen fabric8/fabric8-ui:SNAPSHOT-PR-2282-6 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2282-fabric8-planner.badger.fabric8.io

**Pull request merged**
