### PR TITLE
Revert "add feature-flag on query-module"

### PR DESCRIPTION
**Pull request by sudsen**
Reverts fabric8-ui/fabric8-planner#2748

### CODE REVIEW

**Comment by alien-ike** [comment]
### Ike Plugins (test-keeper)

Thank you @sudsen for this contribution!



It appears that no tests have been added or updated in this PR.

Automated tests give us confidence in shipping reliable software. Please add some as part of this change.

If you are an admin or the reviewer of this PR and you are sure that no test is needed then you can use the command `/ok-without-tests` as a comment to make the status green.


Your plugin configuration is stored in the [file](https://github.com/fabric8-ui/fabric8-planner/blob/f757fec623c0954486ac42fae53a742bef78049f/.ike-prow/test-keeper.yaml).

**Comment by divyanshiGupta** [comment]
@sudsen what does this PR do?

**Comment by alien-ike** [comment]
Hey @sanbornsen! It seems you tried to trigger `/ok-without-tests` command, but this will not have any effect due to insufficient permission. You have to be admin or requested reviewer or pull request approver, but not pull request creator for this command to take an effect.

**Comment by sanbornsen** [comment]
I overlooked the commit message during a review. It should be a **feat** or **fix** type.

**Comment by divyanshiGupta** [comment]
Sorry for that, I missed to write the commit message in the proper format. But was it just because of the commit message? Because I see a lot of commits without that proper format in master. Is it really required to revert the PR? since it is already merged.

**Comment by divyanshiGupta** [comment]
Sorry that I missed the correct format for the commit message.

**Comment by sanbornsen** [comment]
[test]

**Comment by divyanshiGupta** [comment]
[test]

**Pull request merged**
