### PR TITLE
 fix(toast-notifications): Suppress create and update notifications

### PR DESCRIPTION
**Pull request by nimishamukherjee**
### Mandatory
 - [ ] What does this PR do? 
Suppresses the create and update toast notifications.
Now only error notifications will be shown

- [ ] What issue/task does this PR references?
https://github.com/openshiftio/openshift.io/issues/1554

- [ ] Are the tests Included?
___
### Optional
- [ ] Is the documentation Included?

- [ ] Are the Release Notes included?

- [ ] @mention(s) to expected reviewer(s) included

### CODE REVIEW

**Comment by alien-ike** [comment]
### Ike Plugins (test-keeper)

Thank you @nimishamukherjee for this contribution!



It appears that no tests have been added or updated in this PR.

Automated tests give us confidence in shipping reliable software. Please add some as part of this change.

If you are an admin or the reviewer of this PR and you are sure that no test is needed then you can use the command `/ok-without-tests` as a comment to make the status green.


Your plugin configuration is stored in the [file](https://github.com/fabric8-ui/fabric8-planner/blob/75ed9b297593f4ac32c8a34d3dc61174d535a83f/.ike-prow/test-keeper.yaml).

**Comment by Raunak1203** [comment]
[test]

**Comment by Raunak1203** [comment]
[test]

**Comment by Raunak1203** [comment]
[test]

**Comment by Raunak1203** [comment]
[test]

**Comment by nimishamukherjee** [comment]
@Raunak1203 thanks for making the test-keeper happy :)

**Comment by Raunak1203** [comment]
[test]

**Pull request merged**
