### PR TITLE
fix(search): replace with typegroup.name

### PR DESCRIPTION
**Pull request by kwk**
Once the backend merges this PR: https://github.com/fabric8-services/fabric8-wit/pull/1929, the correct field to ask for when searching for type groups is `typegroup.name` and not `$WITGROUP`.

### CODE REVIEW

**Comment by kwk** [comment]
[test]

**Comment by kwk** [comment]
[test]

**Comment by kwk** [comment]
> Reverted. Not backward compatible. Broke preview and prevent prod rollout.
> fabric8-services/fabric8-wit#1930

@aslakknutsen @sanbornsen once this PR https://github.com/openshiftio/saas-openshiftio/pull/675 updates prod, we can merge this one (if it passes the build). Because then the backend supports both, `$WITGROUP` and `typegroup.name` as search fields in prod and prod-preview.

**Comment by sanbornsen** [comment]
@kwk now since the master has gone forward, there are more $WITGROUP in **components_ngrx** directory. Can you please take care of that as well in this PR?

**Comment by kwk** [comment]
[test]

**Comment by kwk** [comment]
[test]

**Comment by fabric8cd** [comment]
@kwk fabric8/fabric8-ui:SNAPSHOT-PR-2483-10 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2483-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@kwk fabric8/fabric8-ui:SNAPSHOT-PR-2483-14 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2483-fabric8-planner.badger.fabric8.io

**Pull request merged**
