### PR TITLE
fix(quick-preview): add close text-fields on outside-click

### PR DESCRIPTION
**Pull request by divyanshiGupta**
<strong>Note: If there are pending changes to the PR, prefix the PR title with "WIP" and add the label "DO NOT MERGE"</strong>

### Mandatory
 - [ ] What does this PR do? 
        This PR implements close text-fields on outside click

- [ ] What issue/task does this PR references?
       Fixes https://github.com/openshiftio/openshift.io/issues/4049

- [ ] Are the tests Included?
      Yes
___
### Optional
- [ ] Is the documentation Included?

- [ ] Are the Release Notes included?

- [ ] @mention(s) to expected reviewer(s) included

### CODE REVIEW

**Comment by divyanshiGupta** [comment]
[test]

**Comment by sahil143** [comment]
[test]

**Comment by sahil143** [comment]
>  I didnt get you, why do we need to add input property in f8-markdown? We are simply checking here if the user has opened the markdown and if he didn't change anything then it will be closed on outside-click otherwise it will not. See this comment here -openshiftio/openshift.io#4049 (comment)

@divyanshiGupta This is an `f8-markdown` specific feature, not planner specific this should be introduced in the component itself. If this is done in ngx-widgets then entities other than planner can also use it.

**Comment by divyanshiGupta** [comment]
[test]

**Comment by divyanshiGupta** [comment]
[test]

**Comment by divyanshiGupta** [comment]
@sahil143 I have updated the version of ngx-widgets in this PR. Please have a look.

**Comment by divyanshiGupta** [comment]
@sahil143 ^^

**Comment by divyanshiGupta** [comment]
@Raunak1203 the description field is not behaving as expected because ngx-widgets version is not updated to 3.1.3 that has the necessary changes.

**Comment by divyanshiGupta** [comment]
[test]

**Comment by divyanshiGupta** [comment]
@sahil143 @Raunak1203 if all your concerns are addressed, can you please approve the PR?

**Comment by Raunak1203** [comment]
@divyanshiGupta description and comment field are editable only if I click the edit button, not on clicking anywhere inside. In prod-preview, if you click anywhere in description and comment box, editing is enabled.
Is this intended change?

**Comment by divyanshiGupta** [comment]
@Raunak1203 yes, because if you look at the description box, it can be opened by clicking inside of it when it is empty but not when it has some text inside, and this is not a consistent behavior.

**Comment by divyanshiGupta** [comment]
@Veethika the other text fields like wi title and dynamic fields can be opened by clicking on it even if they are not empty. On the other hand the  description field is opened when clicked on it when it is empty and not when it has some text. This is not a consistent behavior. According to me all the text fields should open only when clicked on the edit icon.

**Comment by divyanshiGupta** [comment]
@Veethika^^

**Pull request merged**
