### PR TITLE
fix(filter): clear all filter option added to the active filter toolbar

### PR DESCRIPTION
**Pull request by sanbornsen**
This PR fixes following issue 
https://github.com/openshiftio/openshift.io/issues/2450

**Feature:** After adding more than one filter it shows an option to clear all filters together.

### CODE REVIEW

**Comment by fabric8cd** [comment]
@sanbornsen fabric8/fabric8-ui:SNAPSHOT-PR-2492-2 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2492-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@sanbornsen fabric8/fabric8-ui:SNAPSHOT-PR-2492-5 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2492-fabric8-planner.badger.fabric8.io

**Comment by kwk** [comment]
@sanbornsen @nimishamukherjee why was this PR merged? It doesn't contain any test? I thought we have tests now?!

**Comment by rgarg1** [comment]
@kwk @nimishamukherjee I have the same question.

**Pull request merged**
