### PR TITLE
extra checks have been added to the shared pipeline to ensure change authors are project collaborators before deploying snapshot PR

### PR DESCRIPTION
**Pull request by rawlingsj**

### CODE REVIEW

**Comment by rawlingsj** [comment]
NOTE: not using semantic release comments as this is a CI change, no release required

**Comment by fabric8cd** [comment]
@rawlingsj fabric8/fabric8-ui:SNAPSHOT-PR-2196-1 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2196-fabric8-planner.badger.fabric8.io

**Comment by rawlingsj** [comment]
Can this be merged please?

**Comment by fabric8cd** [comment]
@rawlingsj fabric8/fabric8-ui:SNAPSHOT-PR-2196-3 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2196-fabric8-planner.badger.fabric8.io

**Pull request merged**
