### PR TITLE
Board fix

### PR DESCRIPTION
**Pull request by SMahil**
Fix board view issues
1. https://openshift.io/openshiftio/openshiftio/plan/detail/1601
2. https://openshift.io/openshiftio/openshiftio/plan/detail/1602

### CODE REVIEW

**Comment by fabric8cd** [comment]
@SMahil fabric8/fabric8-ui:SNAPSHOT-PR-2463-1 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2463-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@SMahil fabric8/fabric8-ui:SNAPSHOT-PR-2463-3 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2463-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@SMahil fabric8/fabric8-ui:SNAPSHOT-PR-2463-4 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2463-fabric8-planner.badger.fabric8.io

**Comment by rgarg1** [comment]
no selection in quick add

**Comment by rgarg1** [comment]
A full workitem type selector, just like list view page, along with just the workitem title page below that would look good.

**Comment by SMahil** [comment]
@rgarg1 "Why does the workitem type selection set to none by default?"  -  This issue we will track in separate where we will be setting DefaultURL

"We've gotten rid of the workitem description field from the list view quick add. We don't need it in Board view either." - We are not changing design for board now, Whatever we have we should have it working

**Comment by rgarg1** [comment]
@SMahil Could you pls log a defect to track it outside this PR and provide a reference here got tracking.

**Comment by SMahil** [comment]
sure @rgarg1

**Comment by fabric8cd** [comment]
@SMahil fabric8/fabric8-ui:SNAPSHOT-PR-2463-7 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2463-fabric8-planner.badger.fabric8.io

**Comment by rgarg1** [comment]
Can we close this PR @SMahil ?

**Comment by SMahil** [comment]
@rgarg1 Yes can close it as we are revamping the board view

**Pull request closed without merging**
