### PR TITLE
fix(query-tab): fix feature flag issue after ng6 upgrade

### PR DESCRIPTION
**Pull request by rohitkrai03**
<strong>Note: If there are pending changes to the PR, prefix the PR title with "WIP" and add the label "DO NOT MERGE"</strong>

### Mandatory
 - [x] What does this PR do? 
    - Moves `ngx-feature-flag` from dependencies to peerDependencies.
    - Remove unused code for adding feature flag in query tab.
- [ ] What issue/task does this PR references?

- [ ] Are the tests Included?
___
### Optional
- [ ] Is the documentation Included?

- [ ] Are the Release Notes included?

- [ ] @mention(s) to expected reviewer(s) included

### CODE REVIEW

**Comment by divyanshiGupta** [comment]
@rohitkrai03 the changes looks good to me so far. Let's wait for the build to pass.

**Comment by divyanshiGupta** [comment]
[test]

**Comment by jarifibrahim** [comment]
[test]

**Comment by jarifibrahim** [comment]
[test]

**Comment by jarifibrahim** [comment]
[test]

**Comment by jarifibrahim** [comment]
[test]

**Pull request merged**
