### PR TITLE
fix(container): update Dockerfile to use proper steps for planner library integration

### LINKED ISSUE #2443: Update container orchestration with the scripting changes
Broken by #2399

### PR DESCRIPTION
**Pull request by debloper**
Closes #2443

### CODE REVIEW

**Comment by fabric8cd** [comment]
@debloper fabric8/fabric8-ui:SNAPSHOT-PR-2447-3 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2447-fabric8-planner.badger.fabric8.io

**Comment by pranavgore09** [comment]
does it work for you? ` docker build -t fabric8-ui-builder -f Dockerfile .` fails for me

**Comment by debloper** [comment]
`docker build -t fabric8-planner-runtime .` works for me fine (as the default Dockerfile is picked, no need to mention with `-f` and as it's a runtime planner, labeled it accordingly).

Unless you have some customizations in your Dockerfile, there shouldn't be an issue.

**Comment by pranavgore09** [comment]
@debloper yea it worked after `rm -rf node_modules`.
approved, please merge.

**Pull request merged**
