### PR TITLE
fix(detail): Description Field Value goes missing when updating data …

### PR DESCRIPTION
**Pull request by vikram-raj**
…on Quick Preview.

### [ ] What does this PR do? _[Mandatory]_
_Note: If you are still working on the changes, prefix the PR title with "WIP" and add the label "DO NOT MERGE"_

Fix description Field Value goes missing when updating data on Quick Preview 

### [ ] What issue/task does this PR references? _[Mandatory]_

https://github.com/openshiftio/openshift.io/issues/3000
### [ ] Are the tests Included? _[Mandatory]_

NA

### CODE REVIEW

**Comment by alien-ike** [comment]
### Ike Plugins (test-keeper)

Thank you @vikram-raj for this contribution!



It appears that no tests have been added or updated in this PR.

Automated tests give us confidence in shipping reliable software. Please add some as part of this change.

If you are an admin and you are sure that no test is needed then you can use the command `/ok-without-tests` as a comment to make the status green.


For more information please head over to official [documentation](http://arquillian.org/ike-prow-plugins/#_test_keeper_plugin). You can find there how to configure the plugin - for example exclude certain file types so if PR contains only them it won't be checked.

**Comment by rgarg1** [comment]
@vikram-raj The issue seems fixed as I can no longer reproduce it anymore.

As far as tests are concerned, IMHO writing functional tests for this issue would be challenging, so please attempt some Unit Tests. @Raunak1203

**Comment by Raunak1203** [comment]
@rgarg1 in prod-preview if you add a new label this issue can be recreated...So, i asked vikram to add test for this...

**Comment by pranavgore09** [comment]
[test]

**Pull request merged**
