### PR TITLE
fix(tests): Increase Jasmine timeout to 5 minutes

### PR DESCRIPTION
**Pull request by jarifibrahim**
**Running tests Locally**
screenshot from 2018-01-17 12-55-16

**Running tests on CI**
download 15

Summary of PR builds -
- Build 1 - Success
- Build 2 - Success
- Build 3 - Failed - Jenkins Exception (`Cannot contact jenkins-slave-1sk60-fscpd: java.lang.InterruptedException`)
- Build 4 - Failed - `fabric8-ui` npm build failed (`script returned exit code -1`)
- Build 5 - Failed - chrome not reachable
- Build 6 - Success
- Build 7 - Failed - Jenkins Exception (`Could not connect to jenkins-slave-bh97n-zz54w to send interrupt signal to process`)
- Build 8 - Failed - KubernetesClientTimeoutException `io.fabric8.kubernetes.client.KubernetesClientTimeoutException: Timed out waiting for [300000] milliseconds for [Pod] with name:[jenkins-slave-1hkt1-2xmz8] in namespace [cd].`
- Build 9 - Failed - npm build failure `npm ERR! code EINTEGRITY`
- Build 10 - Failed - `Error cloning remote repo 'origin'`
- Build 11 - Failed - npm build failure `npm ERR! code EINTEGRITY`

Successful - 3
Failed - 8

### CODE REVIEW

**Comment by fabric8cd** [comment]
@jarifibrahim fabric8/fabric8-ui:SNAPSHOT-PR-2406-1 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2406-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@jarifibrahim fabric8/fabric8-ui:SNAPSHOT-PR-2406-2 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2406-fabric8-planner.badger.fabric8.io

**Comment by debloper** [comment]
@jarifibrahim if this has less than 50% success rate over 5 runs, try turning that to 10min timeout and rerun 5 times if helps (and have better results).

I understand 10min timeout is awkward, but don't think we have an upperhand here :P

**Comment by jarifibrahim** [comment]
@debloper None of the failures were due to functional test failures. Check the PR description.

**Comment by fabric8cd** [comment]
@jarifibrahim fabric8/fabric8-ui:SNAPSHOT-PR-2406-6 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2406-fabric8-planner.badger.fabric8.io

**Comment by debloper** [comment]
@jarifibrahim I feel I'm repeating myself here, but I didn't say anything about the test-case failures.
Functional test as the whole setup is what I'm talking of and my suggestion was regarding that.

**Comment by debloper** [comment]
To summarize the funcTest result history (feel free to add this in main description):

1. PASS
2. PASS
3. DQ (jenkins-slave down)
4. PASS (build failed)
5. FAIL
6. PASS
7. PASS (build failed)
8. PASS (snapshot failed)
9. DQ (jenkins-slave down)
11. DQ (jenkins-slave down)

Out of 10 runs, 3 are Disqualified, 6 Passed, 1 Failed
3 failed in other stages, which I'm considering PASS for funcTests.

**Comment by jarifibrahim** [comment]
Closing this PR since we'll be using Typescript based tests https://github.com/fabric8-ui/fabric8-planner/pull/2417 which makes this PR obsolete.

**Pull request closed without merging**
