### PR TITLE
fix(work-item-link): Show "No match found!" if API can't find a WI with the search string

### LINKED ISSUE #1874: "No match found" missing for the search which doesn't have results while Linking item
"No match found" missing for the search which doesn't have results while Linking item

Expected:
- In case there is no result for specific search , there should be "No match found" warning for this .

Video Link : https://drive.google.com/a/redhat.com/file/d/0B1qUq_laG6COR2xtSjdzUzJQa0k/view?usp=sharing

### PR DESCRIPTION
**Pull request by debloper**
Closes #1874

### CODE REVIEW

**Comment by fabric8cd** [comment]
@debloper snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1965-fabric8-planner.int.rdu2c.fabric8.io

**Comment by nimishamukherjee** [comment]
defaul

In your PR - "No match found" displayed when the detail's panel opens.

Expected: No match found to be displayed after the user types in the text box.

**Comment by fabric8cd** [comment]
@debloper snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1965-fabric8-planner.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@debloper snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1965-fabric8-planner.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@debloper snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1965-fabric8-planner.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@debloper snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1965-fabric8-planner.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@debloper snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1965-fabric8-planner.int.rdu2c.fabric8.io

**Comment by nimishamukherjee** [comment]
1. Create a work item say workitem1
2. Create another work item say item2
3. In the link section of item2, type wor
It displays "No matches found" for a second and then the matching results are displayed.

**Comment by mindreeper2420** [comment]
@debloper @nimishamukherjee is this based off a UX design that you have, or is this something that you want in the system? Please mark items like this as bugs for @fabric8-uxd to research and provide resolutions for before submitted fixes.

**Comment by debloper** [comment]
Thanks for the suggestion @mindreeper2420, I've filed #2006 and assigned to you.
I've also filed a mirrored issue https://github.com/fabric8io/fabric8-ux/issues/488, just in case (wasn't sure which place would be more apt for a issue like this as none mentioned).

**Comment by mindreeper2420** [comment]
Thanks @debloper. I'll take the issue and add it to our next UX sprint and will update the issue accordingly.

**Comment by fabric8cd** [comment]
@debloper snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1965-fabric8-planner.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@debloper snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1965-fabric8-planner.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@debloper snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1965-fabric8-planner.int.rdu2c.fabric8.io

**Comment by fabric8cd** [comment]
@debloper snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1965-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@debloper snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1965-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@debloper snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1965-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@debloper snapshot fabric8-ui is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1965-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@debloper fabric8/fabric8-ui:SNAPSHOT-PR-1965-11 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1965-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@debloper fabric8/fabric8-ui:SNAPSHOT-PR-1965-12 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1965-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@debloper fabric8/fabric8-ui:SNAPSHOT-PR-1965-13 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1965-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@debloper fabric8/fabric8-ui:SNAPSHOT-PR-1965-16 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1965-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@debloper fabric8/fabric8-ui:SNAPSHOT-PR-1965-17 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1965-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@debloper fabric8/fabric8-ui:SNAPSHOT-PR-1965-19 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1965-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@debloper fabric8/fabric8-ui:SNAPSHOT-PR-1965-20 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1965-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@debloper fabric8/fabric8-ui:SNAPSHOT-PR-1965-22 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1965-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@debloper fabric8/fabric8-ui:SNAPSHOT-PR-1965-23 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1965-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@debloper fabric8/fabric8-ui:SNAPSHOT-PR-1965-24 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1965-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@debloper fabric8/fabric8-ui:SNAPSHOT-PR-1965-25 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1965-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@debloper fabric8/fabric8-ui:SNAPSHOT-PR-1965-26 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1965-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@debloper fabric8/fabric8-ui:SNAPSHOT-PR-1965-27 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1965-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@debloper fabric8/fabric8-ui:SNAPSHOT-PR-1965-28 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1965-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@debloper fabric8/fabric8-ui:SNAPSHOT-PR-1965-29 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1965-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@debloper fabric8/fabric8-ui:SNAPSHOT-PR-1965-4 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1965-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@debloper fabric8/fabric8-ui:SNAPSHOT-PR-1965-2 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1965-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@debloper fabric8/fabric8-ui:SNAPSHOT-PR-1965-4 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-1965-fabric8-planner.badger.fabric8.io

**Comment by debloper** [comment]
Marooned and obsolete.

**Pull request closed without merging**
