### PR TITLE
Add work item link

### PR DESCRIPTION
**Pull request by vikram-raj**
### [ ] What does this PR do? _[Mandatory]_
_Note: If you are still working on the changes, prefix the PR title with "WIP" and add the label "DO NOT MERGE"_

The work item linking was removed initially when we implemented ngrx store. This PR is taking back the work item linking feature using ngrx.

### [ ] What issue/task does this PR references? _[Mandatory]_

issue - https://openshift.io/openshiftio/openshiftio/plan/detail/1976

### [ ] Are the tests Included? _[Mandatory]_

Yes

### CODE REVIEW

**Comment by nimishamukherjee** [comment]
null_id
When I search by ID (mine was a single digit ID - 7), after selection, it shows null

**Comment by Raunak1203** [comment]
@vikram-raj if we click on linked workitem title it opens detail page in new tab..now if i remove workitem link..it is not updated in quickpreview..

**Comment by vikram-raj** [comment]
> @vikram-raj if we click on linked workitem title it opens detail page in new tab..now if i remove workitem link..it is not updated in quickpreview.

This issue has been fixed in https://github.com/fabric8-ui/fabric8-planner/pull/2536/commits/ee0686d3b58213bf9e0e60e843b3a415874ff041

**Comment by vikram-raj** [comment]
> if i'm in detail page and i click linked workitem title it gives 404error, (url changes from plan/detail/1-> to detail/1/detail/2) and throws 404

fix this in https://github.com/fabric8-ui/fabric8-planner/pull/2536/commits/48162d435c9f895ba984d1261866b84e3e6ded11

**Pull request merged**
