### PR TITLE
Type Hierarchy Shortcuts in Sidebar (OSIO-1750)

### PR DESCRIPTION
**Pull request by nimishamukherjee**
Update the type hierarchy shortcuts in sidebar as per [OSIO-1750](https://openshift.io/openshiftio/openshiftio/plan/detail/1750)

This PR depends on https://github.com/fabric8-ui/ngx-fabric8-wit/pull/172. Until then the builds will fail.

In this PR,
- Scenarios, Experiences, and Requirements are displayed based on type hierarchy JSON API response.
If show-in-sidebar is true, the type hierarchy is displayed in the side panel.
- The URL uses $WITGROUP:value format. Like $WITGROUP:Requirements

https://docs.google.com/presentation/d/19vRm9GTG_3CEB89syBNzUrJvXZeak-KXs_WmpLd7CZE/edit

TO DO in separate PRs:
- Iterations based on type hierarchy

### CODE REVIEW

**Comment by fabric8cd** [comment]
@nimishamukherjee fabric8/fabric8-ui:SNAPSHOT-PR-2380-22 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2380-fabric8-planner.badger.fabric8.io

**Comment by jarifibrahim** [comment]
@nimishamukherjee From [OSIO-1750](https://openshift.io/openshiftio/openshiftio/plan/detail/1750)
>The user can modify the query using the toolbar and add new query terms or switch between flat and hierarchical view.

Is this implemented in this PR?

**Comment by rgarg1** [comment]
@nimishamukherjee 
I do not see the query displayed in the toolbar. The Acceptance criteria asks for it:
**The toolbar will reflect the query, including the current guided type hierarchy level**

**Comment by Raunak1203** [comment]
@nimishamukherjee 
If i select Experience from left panel and add a child workitem from a  workitem. It goes to waiting state and a child work item is not created.

**Comment by Raunak1203** [comment]
Overlapping message on adding new workitem.
text

**Comment by fabric8cd** [comment]
@nimishamukherjee fabric8/fabric8-ui:SNAPSHOT-PR-2380-23 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2380-fabric8-planner.badger.fabric8.io

**Comment by michaelkleinhenz** [comment]
Please make sure we only report issues here that are connected to the actual PR. Please check against current prod-preview for that. For example, the notification issue is not an issue with this PR. :-)

**Comment by fabric8cd** [comment]
@nimishamukherjee fabric8/fabric8-ui:SNAPSHOT-PR-2380-28 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2380-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@nimishamukherjee fabric8/fabric8-ui:SNAPSHOT-PR-2380-29 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2380-fabric8-planner.badger.fabric8.io

**Comment by nimishamukherjee** [comment]
@rgarg1 the following has been fixed. Please verify.
> A WI is not displayed in the tree view if it happens to be a child of any other WI. E.g. I've a structure like this: Scen1 -> Exp1 -> Feat1 -> Task1. Now when I select Experiences from the left panel, Exp1 is NOT displayed. Only workitems that are unparented are displayed in the query. Something is fundamentally broken!

@jarifibrahim the following has been fixed. Please verify.
> Add child work item is broken. It works fine on prod-preview.

@Raunak1203 the following has been fixed. Please verify.
> If i select Experience from left panel and add a child workitem from a workitem. It goes to waiting state and a child work item is not created.

@Raunak1203 the overlapping notification is beyond this PR.

**Comment by rgarg1** [comment]
@nimishamukherjee 

The issue of missing workitems is resolved and I can now see the parented workitems too in the tree view. However, this introduces another deviation from the proposed wire-frames:
https://docs.google.com/presentation/d/19vRm9GTG_3CEB89syBNzUrJvXZeak-KXs_WmpLd7CZE/edit#slide=id.g2b2bb7e52b_0_169

As per the layout we agreed on, for all matching workitem entries in a tree view, their parents should also be displayed. In the current implementation, the parents are not displayed. For example, I've a structure like this: Scen1 -> Exp1 -> Feat1 -> Task1. Now when I select Experiences from the left panel, Exp1 is displayed, but without Scen1, which should be displayed as per the wire-frames.

I'm not saying that this is wrong, in fact I prefer this approach, however to accept this, we need PMs approval.

**Comment by nimishamukherjee** [comment]
@rgarg1 the parent display is not a part of this PR. That would go into the ngx-datatables. That also has a dependency on the backend.

**Comment by Raunak1203** [comment]
The issue of not able to create a childWorkItem is resolved

**Pull request merged**
