### PR TITLE
feat(switch): created a new component switch.

### PR DESCRIPTION
**Pull request by vikram-raj**

### CODE REVIEW

**Comment by fabric8cd** [comment]
@vikram-raj fabric8/fabric8-ui:SNAPSHOT-PR-2106-1 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2106-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@vikram-raj fabric8/fabric8-ui:SNAPSHOT-PR-2106-3 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2106-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@vikram-raj fabric8/fabric8-ui:SNAPSHOT-PR-2106-4 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2106-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@vikram-raj fabric8/fabric8-ui:SNAPSHOT-PR-2106-5 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2106-fabric8-planner.badger.fabric8.io

**Comment by nimishamukherjee** [comment]
@vikram-raj next sprint, we can move the switch component to ngx-widgets.

**Pull request merged**
