### PR TITLE
fix(tests): remove redundant tests

### PR DESCRIPTION
**Pull request by sahil143**
- [ ] What does this PR do? 
The test being removed doesn't actually do anything. It tests the `orderBy` and `sort` method (which we don't really have to do :wink:). The entire test and the file is removed.

### CODE REVIEW

**Comment by jarifibrahim** [comment]
[test]

**Comment by alien-ike** [comment]
### Ike Plugins (test-keeper)

Thank you @sahil143 for this contribution!



It appears that no tests have been added or updated in this PR.

Automated tests give us confidence in shipping reliable software. Please add some as part of this change.

If you are an admin or the reviewer of this PR and you are sure that no test is needed then you can use the command `/ok-without-tests` as a comment to make the status green.


Your plugin configuration is stored in the [file](https://github.com/fabric8-ui/fabric8-planner/blob/4152b688f1e547ed6fc5e324042985cb75dfa56b/.ike-prow/test-keeper.yaml).

**Comment by sahil143** [comment]
[test]

**Comment by jarifibrahim** [comment]
[test]

**Pull request merged**
