### PR TITLE
fix(link): more usecase cover for link feature

### PR DESCRIPTION
**Pull request by vikram-raj**
### [ ] What does this PR do? _[Mandatory]_
_Note: If you are still working on the changes, prefix the PR title with "WIP" and add the label "DO NOT MERGE"_

 - Disable browser autocomplete for search work item field.
 - After the parent-child linking if the target work item is not present in the list then update the list will get updated with target work item.
 - After the parent-child linking if the source work item is not present in the list then update the list will get updated with source work item.
 - If both source and target are not present in the list then the list will not get updated.

### [ ] What issue/task does this PR references? _[Mandatory]_

https://openshift.io/openshiftio/openshiftio/plan/detail/1976

### CODE REVIEW

**Comment by alien-ike** [comment]
### Ike Plugins (test-keeper)

Thank you @vikram-raj for this contribution!



It appears that no tests have been added or updated in this PR.

Automated tests give us confidence in shipping reliable software. Please add some as part of this change.

If you are an admin or the reviewer of this PR and you are sure that no test is needed then you can use the command `/ok-without-tests` as a comment to make the status green.


For more information please head over to official [documentation](http://arquillian.org/ike-prow-plugins/#_test_keeper_plugin). You can find there how to configure the plugin - for example exclude certain file types so if PR contains only them it won't be checked.

**Comment by rgarg1** [comment]
No tests. Build failed too.

**Comment by Raunak1203** [comment]
[test]

**Comment by vikram-raj** [comment]
[test]

**Comment by vikram-raj** [comment]
[test]

**Comment by vikram-raj** [comment]
This PR is outdated after data normalization. Need to do some work on this. So closing this for now.

**Pull request closed without merging**
