### PR TITLE
fix(test): Update WI link tests

### PR DESCRIPTION
**Pull request by jarifibrahim**
This PR fixes all the tests related to linking work items.

### CODE REVIEW

**Comment by fabric8cd** [comment]
@jarifibrahim fabric8/fabric8-ui:SNAPSHOT-PR-2306-1 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2306-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@jarifibrahim fabric8/fabric8-ui:SNAPSHOT-PR-2306-2 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2306-fabric8-planner.badger.fabric8.io

**Comment by jarifibrahim** [comment]
Closing this PR as the commit has already been merged via https://github.com/fabric8-ui/fabric8-planner/pull/2313

**Comment by fabric8cd** [comment]
@jarifibrahim fabric8/fabric8-ui:SNAPSHOT-PR-2306-3 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2306-fabric8-planner.badger.fabric8.io

**Pull request closed without merging**
