### PR TITLE
Update local docker

### PR DESCRIPTION
**Pull request by ldimaggi**
Do not merge - WIP - unit tests are running - functional tests are failing to run

### CODE REVIEW

**Comment by fabric8cd** [comment]
@ldimaggi fabric8/fabric8-ui:SNAPSHOT-PR-2072-2 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2072-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@ldimaggi fabric8/fabric8-ui:SNAPSHOT-PR-2072-3 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2072-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@ldimaggi fabric8/fabric8-ui:SNAPSHOT-PR-2072-4 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2072-fabric8-planner.badger.fabric8.io

**Comment by osiotest314** [comment]
DO NOT COMMIT THIS PR - it should simply be closed - https://github.com/fabric8-ui/fabric8-planner/pull/2080 makes this PR obsolete. Thx!

**Pull request closed without merging**
