### PR TITLE
feat(customquery): added delete custom query feature

### PR DESCRIPTION
**Pull request by vikram-raj**
### [ ] What does this PR do? _[Mandatory]_
_Note: If you are still working on the changes, prefix the PR title with "WIP" and add the label "DO NOT MERGE"_

This PR contain delete feature of the custom query.

### [ ] What issue/task does this PR references? _[Mandatory]_

https://openshift.io/openshiftio/openshiftio/plan/detail/2198

### [ ] Are the tests Included? _[Mandatory]_

Yes

### CODE REVIEW

**Comment by alien-ike** [comment]
### Ike Plugins (test-keeper)

Thank you @vikram-raj for this contribution!



It appears that no tests have been added or updated in this PR.

Automated tests give us confidence in shipping reliable software. Please add some as part of this change.

If you are an admin or the reviewer of this PR and you are sure that no test is needed then you can use the command `/ok-without-tests` as a comment to make the status green.


For more information please head over to official [documentation](http://arquillian.org/ike-prow-plugins/#_test_keeper_plugin). You can find there how to configure the plugin - for example exclude certain file types so if PR contains only them it won't be checked.

**Comment by fabric8cd** [comment]
@vikram-raj fabric8/fabric8-ui:SNAPSHOT-PR-2590-3 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2590-fabric8-planner.badger.fabric8.io

**Comment by vikram-raj** [comment]
> 1) After deleting a query, Saving a custom query option is missing. Could you please check

@Raunak1203 Fixed. please check.

>2) If I delete a custom query then applied filters should also be removed?

The filter should remain applied. Right @nimishamukherjee?

**Comment by nimishamukherjee** [comment]
@vikram-raj @Raunak1203 let us retain the filters.
Deleting a custom query is a specific action - delete query and nothing beyond that. The applied filters can remain

**Comment by vikram-raj** [comment]
@Raunak1203 I added confirmation modal for delete custom query and Modified test. Can you please review this PR again.

**Comment by Raunak1203** [comment]
LGTM

**Comment by vikram-raj** [comment]
@Raunak1203 Issue has been resolved please check.

**Comment by Raunak1203** [comment]
[test]

**Comment by vikram-raj** [comment]
[test]

**Pull request merged**
