### PR TITLE
fix(quick-add): fix focus on qa title after enter

### PR DESCRIPTION
**Pull request by SMahil**
Issue No . https://github.com/openshiftio/openshift.io/issues/1993

### CODE REVIEW

**Comment by fabric8cd** [comment]
@SMahil fabric8/fabric8-ui:SNAPSHOT-PR-2424-1 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2424-fabric8-planner.badger.fabric8.io

**Comment by rgarg1** [comment]
Quick-add in inline-add is not working in similar way. Is that a know limitation with the datatable?

**Comment by SMahil** [comment]
@rgarg1 after changing type autofocus is working for me.
and for Inline quick add, If we need it to work in similar manner we can track that issue separately

**Comment by fabric8cd** [comment]
@SMahil fabric8/fabric8-ui:SNAPSHOT-PR-2424-3 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2424-fabric8-planner.badger.fabric8.io

**Comment by rgarg1** [comment]
LGTM @SMahil

**Pull request merged**
