### PR TITLE
fix(iteration): updated the mock data and iteration service

### PR DESCRIPTION
**Pull request by vikram-raj**
WORK IN PROGRESS.
- UI is ready but the integration with the core is not done.

### CODE REVIEW

**Comment by fabric8cd** [comment]
@vikram-raj fabric8/fabric8-ui:SNAPSHOT-PR-2108-1 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2108-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@vikram-raj fabric8/fabric8-ui:SNAPSHOT-PR-2108-2 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2108-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@vikram-raj fabric8/fabric8-ui:SNAPSHOT-PR-2108-3 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2108-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@vikram-raj fabric8/fabric8-ui:SNAPSHOT-PR-2108-5 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2108-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@vikram-raj fabric8/fabric8-ui:SNAPSHOT-PR-2108-6 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2108-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@vikram-raj fabric8/fabric8-ui:SNAPSHOT-PR-2108-7 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2108-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@vikram-raj fabric8/fabric8-ui:SNAPSHOT-PR-2108-8 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2108-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@vikram-raj fabric8/fabric8-ui:SNAPSHOT-PR-2108-9 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2108-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@vikram-raj fabric8/fabric8-ui:SNAPSHOT-PR-2108-10 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2108-fabric8-planner.badger.fabric8.io

**Comment by rgarg1** [comment]
1) The attached warning should not display if no iteration exists, like in my case.
2) Space missing between text
3) Need some UX inputs on how to display this better
no date set warning

**Comment by fabric8cd** [comment]
@vikram-raj fabric8/fabric8-ui:SNAPSHOT-PR-2108-11 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2108-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@vikram-raj fabric8/fabric8-ui:SNAPSHOT-PR-2108-12 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2108-fabric8-planner.badger.fabric8.io

**Comment by rgarg1** [comment]
@vikram-raj 
Few more issues. Are we still waiting on more merges?:
1) Making the iteration Force Active has no effect
2) Iteration Kebab menu options stay open even after clicking away from them
3) How do I know if the iteration is closed. No visual indication.

**Comment by vikram-raj** [comment]
@rgarg1 Yes, active iteration will not work. Because this snapshot is point to production API and backend changes for active iteration are still not in production. So, once this PR https://github.com/openshiftio/saas-openshiftio/pull/209 will get merged then you can see the effect of active iteration.

**Comment by fabric8cd** [comment]
@vikram-raj fabric8/fabric8-ui:SNAPSHOT-PR-2108-18 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2108-fabric8-planner.badger.fabric8.io

**Pull request merged**
