### PR TITLE
fix(dropdown): add directive for clicking outside of an element 

### PR DESCRIPTION
**Pull request by sahil143**
<strong>Note: If there are pending changes to the PR, prefix the PR title with "WIP" and add the label "DO NOT MERGE"</strong>

### Mandatory
 - [ ] What does this PR do? 
- added a directive to check for outside click
- use the directive in select-dropdown
- datatable-config dropdown and quick-preview doesn't open simultaneously

- [ ] What issue/task does this PR references?
https://github.com/openshiftio/openshift.io/issues/3211

- [ ] Are the tests Included?
Tests  #2596 
___
### Optional
- [ ] Is the documentation Included?

- [ ] Are the Release Notes included?

- [ ] @mention(s) to expected reviewer(s) included

### CODE REVIEW

**Comment by alien-ike** [comment]
### Ike Plugins (test-keeper)

Thank you @sahil143 for this contribution!



It appears that no tests have been added or updated in this PR.

Automated tests give us confidence in shipping reliable software. Please add some as part of this change.

If you are an admin or the reviewer of this PR and you are sure that no test is needed then you can use the command `/ok-without-tests` as a comment to make the status green.


Your plugin configuration is stored in the [file](https://github.com/fabric8-ui/fabric8-planner/ddbd050d690a12dbc74baa8590426ea2c726eab4/test-keeper.yml).

**Comment by nimishamukherjee** [comment]
@sahil143 @divyanshiGupta is the outside click for closing tooltips a part of this PR?

**Comment by sahil143** [comment]
@nimishamukherjee No, This Pr is only for Select-Dropdown and table-config dropdown

**Comment by divyanshiGupta** [comment]
@nimishamukherjee close infotip on outside click is not a part of this PR as this directive won't be used for closing the infotip when clicked outside.

**Comment by nimishamukherjee** [comment]
[test]

**Pull request merged**
