### PR TITLE
fix(modal): Fixed comment delete modal, added generic modal component.

### PR DESCRIPTION
**Pull request by michaelkleinhenz**

### CODE REVIEW

**Comment by fabric8cd** [comment]
@michaelkleinhenz fabric8/fabric8-ui:SNAPSHOT-PR-2303-1 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2303-fabric8-planner.badger.fabric8.io

**Comment by nimishamukherjee** [comment]
@michaelkleinhenz in detail view the modal does not show up.
It works perfectly for quick preview.

**Comment by michaelkleinhenz** [comment]
@nimishamukherjee fixed.

**Comment by fabric8cd** [comment]
@michaelkleinhenz fabric8/fabric8-ui:SNAPSHOT-PR-2303-2 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2303-fabric8-planner.badger.fabric8.io

**Pull request merged**
