### PR TITLE
fix(iteration): Allow user to select past and future start date.

### PR DESCRIPTION
**Pull request by vikram-raj**
<strong>Note: If there are pending changes to the PR, prefix the PR title with "WIP" and add the label "DO NOT MERGE"</strong>

### Mandatory
 - [x] What does this PR do? 
Allow the user to select Past or future start date.
- [x] What issue/task does this PR references?
https://github.com/openshiftio/openshift.io/issues/2506
- [ ] Are the tests Included?
No

### CODE REVIEW

**Comment by alien-ike** [comment]
### Ike Plugins (test-keeper)

Thank you @vikram-raj for this contribution!



It appears that no tests have been added or updated in this PR.

Automated tests give us confidence in shipping reliable software. Please add some as part of this change.

If you are an admin or the reviewer of this PR and you are sure that no test is needed then you can use the command `/ok-without-tests` as a comment to make the status green.


Your plugin configuration is stored in the [file](https://github.com/fabric8-ui/fabric8-planner/4637b4a6c03e49c940c40f5f36511bc6a0597306/test-keeper.yml).

**Comment by nimishamukherjee** [comment]
[test]

**Comment by Raunak1203** [comment]
[test]

**Comment by vikram-raj** [comment]
@nimishamukherjee I investigate the issue that @Raunak1203  reported on this PR. This is the issue with the calendar component and that issue also reported here https://github.com/kekeh/mydatepicker/issues/440. Auther of the component say it has been fixed in the updated version and I tried the updated version of the component and it doesn't work. So for now, I disable the year selector in the component. So that planner does not get hang if someone clicks on year selector.

**Comment by nimishamukherjee** [comment]
Makes sense @vikram-raj 
@Raunak1203 we can merge the PR with selection of previous year being disabled.

**Comment by nimishamukherjee** [comment]
[test]

**Comment by nimishamukherjee** [comment]
[test]

**Comment by rgarg1** [comment]
@vikram-raj LGTM. I can now select all past and future dates. The issues observed are:

- The arrows to move back and forth months often display in gray color, despite being clickable. Functionally, the buttons are usable; just a cosmetic issue

- Clicking on year freezes the edit pane. But I guess you've already addressed this one.

**Comment by Raunak1203** [comment]
[test]

**Pull request merged**
