### PR TITLE
Iterations shortcuts in sidebar [osio-1751]

### PR DESCRIPTION
**Pull request by nimishamukherjee**
Introduces the updated iterations shortcuts [osio-1751](https://openshift.io/openshiftio/openshiftio/plan/detail/1751)

### CODE REVIEW

**Comment by fabric8cd** [comment]
@nimishamukherjee fabric8/fabric8-ui:SNAPSHOT-PR-2409-5 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2409-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@nimishamukherjee fabric8/fabric8-ui:SNAPSHOT-PR-2409-6 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2409-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@nimishamukherjee fabric8/fabric8-ui:SNAPSHOT-PR-2409-7 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2409-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@nimishamukherjee fabric8/fabric8-ui:SNAPSHOT-PR-2409-26 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2409-fabric8-planner.badger.fabric8.io

**Comment by rgarg1** [comment]
iter sidebar issues

**Comment by rgarg1** [comment]
One more issue:

4. Hovering over the clickable iteration name in the Active section, displays no clickable indication (hand icon)

**Comment by nimishamukherjee** [comment]
@rgarg1 the following have been fixed:

- [ ] The quick-add workitem types are messed up when an Active iteration is selected from the 'Active iterations' section. The options need to match to Execution
- [ ] The iterations tree is messed up in case there are long iteration names. Even the kebab menu is difficult to locate
- [ ] Hovering over the click-able iteration name in the Active section, displays no click-able indication (hand icon)


Regarding
> Iteration name at level 4 of the tree is improperly aligned so a parent-child relationship is not clearly evident

For now we have decided to allow indenting for three levels only. Any level beyond that will align at the same level. We need to discuss and finalise on the eventual behaviour as it does not make sense to have ten levels of nested iterations and a huge horizontal scroll.

**Comment by fabric8cd** [comment]
@nimishamukherjee fabric8/fabric8-ui:SNAPSHOT-PR-2409-34 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2409-fabric8-planner.badger.fabric8.io

**Comment by rgarg1** [comment]
@nimishamukherjee 

> The quick-add workitem types are messed up when an Active iteration is selected from the 'Active iterations' section. The options need to match to Execution
LGTM.

> Hovering over the click-able iteration name in the Active section, displays no click-able indication (hand icon)
LGTM.

> The iterations tree is messed up in case there are long iteration names. Even the kebab menu is difficult to locate
I can still see this issue exists. See the image attached below.

> we have decided to allow indenting for three levels only. Any level beyond that will align at the same level. 
Sounds fair to me. Do we have UX sign-off on this? Let's discuss this with @SMahil too

A new issue that is a deviation from the proposed wire frames. Selecting an iteration should also mark the iteration (if its Active) with a tick in the Active panel. refer here:
https://redhat.invisionapp.com/share/NVEWGDU4W#/screens/269980285

iter left bar

**Comment by fabric8cd** [comment]
@nimishamukherjee fabric8/fabric8-ui:SNAPSHOT-PR-2409-35 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2409-fabric8-planner.badger.fabric8.io

**Comment by nimishamukherjee** [comment]
Please verify the fix for iteration tree. This also works for three levels.

@SMahil @rgarg1 I have created a feature - https://openshift.io/openshiftio/openshiftio/plan/detail/1837, to discuss and propose nested iteration behaviour to PM.

**Comment by nimishamukherjee** [comment]
@rgarg1 for the active iteration tick mark refer to https://redhat.invisionapp.com/share/NVEWGDU4W#/screens/269980285

**Comment by rgarg1** [comment]
@SMahil 

We should truncate longer strings uni-formally i.e. either trim the start of the string or the end of it. Currently, we are truncating the first part in the Active section, but trimming the last part in iteration tree view. Have a look.

long iter names

@nimishamukherjee 
The tick mark issue is the only pending thing that blocks this PR.

**Comment by SMahil** [comment]
@rgarg1 In active iteration list we are having spacename/iterationname so focusing more on iteration name and as a result truncating from start. But in iteration tree we are only having iteration name so truncating it from end

**Comment by rgarg1** [comment]
I see your point @SMahil. Any specific reason to focus on Area name in active section? With very long iteration names (not practical though), I'm finding difficult to identify my iteration between the two sections.

@nimishamukherjee I couldn't find the discussion you wanted me to look at in the wire frames. Could you please give me a gist of it.

**Comment by nimishamukherjee** [comment]
@rgarg1 
active

The white tick mark indicates which active iteration the user is viewing.

**Comment by rgarg1** [comment]
@nimishamukherjee 
Oh yes. I know this and hence I commented that whenver an iteration is selected from the iterations tree view, the corresponding entry in active iterations section must show the tick bar too (if the iter is active). It isn't happening now.

**Comment by nimishamukherjee** [comment]
@rgarg1 I have created https://openshift.io/openshiftio/openshiftio/plan/detail/1838 for the highlight issue and I am working on it. Can we merge this PR.

**Comment by rgarg1** [comment]
Sure @nimishamukherjee. The issue could be tracked outside the PR.

**Pull request merged**
