### PR TITLE
fix(list): make horizontal scroll bar visible

### PR DESCRIPTION
**Pull request by vikram-raj**

### CODE REVIEW

**Comment by fabric8cd** [comment]
@vikram-raj fabric8/fabric8-ui:SNAPSHOT-PR-2433-1 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2433-fabric8-planner.badger.fabric8.io

**Comment by SMahil** [comment]
scroll doesn't show up until and unless i start scrolling
screen shot 2018-02-07 at 12 25 53 pm

**Comment by vikram-raj** [comment]
@SMahil That's MAC default behavior, we can not change that until. For that, we have to implement custom scrollbar.

**Comment by nimishamukherjee** [comment]
@SMahil do you have a fix for Mac? If yes, add it to this PR.
It works on Fedora Firefox and Chrome.

**Comment by SMahil** [comment]
@nimishamukherjee If we want to change the default behaviour it should be applicable for all instances

**Comment by rgarg1** [comment]
LGTM on Fedora at 1440x900 resolution.

**Comment by fabric8cd** [comment]
@vikram-raj fabric8/fabric8-ui:SNAPSHOT-PR-2433-2 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2433-fabric8-planner.badger.fabric8.io

**Comment by vikram-raj** [comment]
@nimishamukherjee Agree. If we are going to change the default behavior of scrollbar for MAC then we have to change it into the entire OSIO otherwise there is inconsistency.

**Pull request merged**
