### PR TITLE
Added npm-shrinkwrap.json for locking dependency versions

### PR DESCRIPTION
**Pull request by samuzzal-choudhury**
### [ ] What does this PR do? _[Mandatory]_
_Note: If you are still working on the changes, prefix the PR title with "WIP" and add the label "DO NOT MERGE"_
This PR introduces an npm-shrinkwrap.json file to the project. NPM shrinkwrap locks the version of all direct and transitive dependencies which are used by the application.

### [ ] What issue/task does this PR references? _[Mandatory]_

https://github.com/openshiftio/openshift.io/issues/2774

### [ ] Are the tests Included? _[Mandatory]_

Not applicable. This PR will rely on the existing tests.

### CODE REVIEW

**Comment by jarifibrahim** [comment]
[test]

**Comment by alien-ike** [comment]
### Ike Plugins (test-keeper)

Thank you @samuzzal-choudhury for this contribution!



It appears that no tests have been added or updated in this PR.

Automated tests give us confidence in shipping reliable software. Please add some as part of this change.

If you are an admin and you are sure that no test is needed then you can use the command `/ok-without-tests` as a comment to make the status green.


For more information please head over to official [documentation](http://arquillian.org/ike-prow-plugins/#_test_keeper_plugin). You can find there how to configure the plugin - for example exclude certain file types so if PR contains only them it won't be checked.

**Comment by nimishamukherjee** [comment]
[test]

**Comment by debloper** [comment]
This needs proper discussion to weigh the pros/cons of using npm-shrinkwrap for our purpose.

Planner being a library (so far) it's better to stick with `package-lock.json` - as the value that shrink-wrap brings in is a theoretical standpoint with really thin practical advantage. The disadvantage, however, is a lot (hundreds) of packages to be duplicate-installed for even patch-version differences (in to the application planner is integrated with).

**Comment by joshuawilson** [comment]
We do not need to lock deps on a lib. Closing this.

**Pull request closed without merging**
