### PR TITLE
fix(datatable): update rh-ngx-datatable version

### PR DESCRIPTION
**Pull request by sahil143**
<strong>Note: If there are pending changes to the PR, prefix the PR title with "WIP" and add the label "DO NOT MERGE"</strong>

### Mandatory
 - [x] What does this PR do? 
Update rh-ngx-datatable version:
 fixes the issue of overlapping rows in Safari 
- [ ] What issue/task does this PR references?

- [ ] Are the tests Included?
ok-without-tests
___
### Optional
- [ ] Is the documentation Included?

- [ ] Are the Release Notes included?

- [ ] @mention(s) to expected reviewer(s) included

### CODE REVIEW

**Comment by kpiwko** [comment]
Hi @sahil143 where can I get changes added to rh-ngx-datatable in 12.0.16? I was not able to find the repo at github and package.json here https://www.npmjs.com/package/rh-ngx-datatable points to upstream repo.

**Comment by sahil143** [comment]
@kpiwko we manage our own fork. You can find the code [here](https://github.com/sahil143/ngx-datatable/tree/rh-master) (this is the latest).

**Comment by kpiwko** [comment]
Thanks @sahil143 . I've tried to modify css using your suggestions but I was not able to do so for all elements:
```
@kpiwko if you want to modify the function I would suggest you locally setup rh-ngx-datatable, Otherwise  you can just directly change the translate-3d property on datatable-row-wrapper element in browser to see the effects.
```

I'll ask for prod-preview account to check there.

**Comment by kpiwko** [comment]
thanks @sahil143 I can confirm this fixes problem in Safari 11.1, checked on prod-preview.

I also haven't noticed any impact in Chrome.

My only comment would be that isSafari function could have been removed from rh-ngx-datatable function as this is now a dead code - but for that I'll create a separate issue.

**Comment by kpiwko** [comment]
Safari:
screen shot 2018-05-17 at 08 53 06

Chrome:
screen shot 2018-05-17 at 08 53 00

**Comment by sahil143** [comment]
Thanks for the review @kpiwko. I'm not able to reproduce the dragNdrop issue in chrome. 
For safari dragNdrop is working but there is no visual indication where the element is being dropped and drag handle is duplicating(as you showed in screenshot above). I will fix these in a seperate PR. I have created an [issue](https://github.com/openshiftio/openshift.io/issues/3582) to track it. Please comment there if i missed something.

**Comment by kpiwko** [comment]
Thanks @sahil143 . TBH, I haven't noticed there is a problem with DnD handle - the screenshots were intended to show that text renders correctly in Safari now and there is no regression in rendering in Chrome :-). @nimishamukherjee @sanbornsen could you give this issue a 👍 so Sahil can proceed with merge? Thanks!

**Pull request merged**
