### PR TITLE
fix(wit): Added tooltips to type icons. Fixes #804

### LINKED ISSUE #804: All workitem icon types are the same as of January 23
See the attached screenshot - only one icon is used for all work item types:

screenshot from 2017-01-23 10-13-20

### PR DESCRIPTION
**Pull request by michaelkleinhenz**
Fixes #804, adds tooltips to WIT icons in detail view and quick preview.

### CODE REVIEW

**Comment by fabric8cd** [comment]
@michaelkleinhenz fabric8/fabric8-ui:SNAPSHOT-PR-2167-1 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2167-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@michaelkleinhenz fabric8/fabric8-ui:SNAPSHOT-PR-2167-3 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2167-fabric8-planner.badger.fabric8.io

**Comment by rgarg1** [comment]
Looks great @michaelkleinhenz

**Comment by fabric8cd** [comment]
@michaelkleinhenz fabric8/fabric8-ui:SNAPSHOT-PR-2167-4 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2167-fabric8-planner.badger.fabric8.io

**Pull request merged**
