### PR TITLE
fix(guidedtype): add guided work item type for iteration

### PR DESCRIPTION
**Pull request by vikram-raj**

### CODE REVIEW

**Comment by fabric8cd** [comment]
@vikram-raj fabric8/fabric8-ui:SNAPSHOT-PR-2129-1 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2129-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@vikram-raj fabric8/fabric8-ui:SNAPSHOT-PR-2129-2 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2129-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@vikram-raj fabric8/fabric8-ui:SNAPSHOT-PR-2129-2 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2129-fabric8-planner.badger.fabric8.io

**Comment by nimishamukherjee** [comment]
[test]

**Comment by fabric8cd** [comment]
@vikram-raj fabric8/fabric8-ui:SNAPSHOT-PR-2129-5 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2129-fabric8-planner.badger.fabric8.io

**Pull request merged**
