### PR TITLE
fix(inline-input): fix border to have consistency

### PR DESCRIPTION
**Pull request by SMahil**
Issue: https://github.com/openshiftio/openshift.io/issues/2284

### CODE REVIEW

**Comment by fabric8cd** [comment]
@SMahil fabric8/fabric8-ui:SNAPSHOT-PR-2457-1 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2457-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@SMahil fabric8/fabric8-ui:SNAPSHOT-PR-2457-3 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2457-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@SMahil fabric8/fabric8-ui:SNAPSHOT-PR-2457-4 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2457-fabric8-planner.badger.fabric8.io

**Comment by SMahil** [comment]
normal state: screen shot 2018-02-23 at 10 43 39 am
hover state: screen shot 2018-02-23 at 10 43 48 am

**Comment by fabric8cd** [comment]
@SMahil fabric8/fabric8-ui:SNAPSHOT-PR-2457-5 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2457-fabric8-planner.badger.fabric8.io

**Comment by fabric8cd** [comment]
@SMahil fabric8/fabric8-ui:SNAPSHOT-PR-2457-6 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2457-fabric8-planner.badger.fabric8.io

**Pull request merged**
