### PR TITLE
fix(label): Filter by label on click label in list page fixed

### PR DESCRIPTION
**Pull request by sanbornsen**

### CODE REVIEW

**Comment by fabric8cd** [comment]
@sanbornsen fabric8/fabric8-ui:SNAPSHOT-PR-2285-1 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2285-fabric8-planner.badger.fabric8.io

**Comment by jarifibrahim** [comment]
@sanbornsen When I click on any label it clears the existing filter and applies only the new label filter.
The filter for the selected label should be applied (appended) to the existing filter, right?

**Comment by sanbornsen** [comment]
No, when you click on the label it should clear up everything and only show the that label filtered.

**Comment by nimishamukherjee** [comment]
@jarifibrahim @sanbornsen I propose that we merge this issue in the current state.
The current label behaviour is modelled on GitHub's label behaviour.
UX can evaluate this. I have created a task https://openshift.io/openshiftio/openshiftio/plan/detail/1597.
Let me know if this works?

**Comment by fabric8cd** [comment]
@sanbornsen fabric8/fabric8-ui:SNAPSHOT-PR-2285-2 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2285-fabric8-planner.badger.fabric8.io

**Comment by jarifibrahim** [comment]
@sanbornsen @nimishamukherjee This PR can be merged.

**Comment by rgarg1** [comment]
Fixed!

**Pull request merged**
