### PR TITLE
fix(tree/flat-list): bug fixes in flat-list and tree-view

### PR DESCRIPTION
**Pull request by sahil143**
This PR fixes these bugs:
1. WI are not updated when you switch from flat-list to tree-view or vice-versa
            Steps to reproduce: 
- tree-view: off (switch to flat list)
- update the title of any WI (say WI id 3)
- switch to tree-view (tree-view: on)
- title of WI id 3 is not updated in tree-view

2. Assignees and Creator for WorkItems in `included` section are not resolved when WI's are loaded in `tree-view: off` i.e. flat-list

### CODE REVIEW

**Comment by fabric8cd** [comment]
@sahil143 fabric8/fabric8-ui:SNAPSHOT-PR-2440-1 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2440-fabric8-planner.badger.fabric8.io

**Comment by sahil143** [comment]
@kwk considering you are talking about unit tests. This has been raised before and From what I can understand is that we are not writing unit tests for any of the components at the moment because of the major revamp coming with ngrx.

**Comment by kwk** [comment]
@sahil143 when is that coming?

**Comment by sahil143** [comment]
@kwk By the end of this sprint.

**Comment by michaelkleinhenz** [comment]
@kwk @sahil143 different things here:

- ngrx and data infra in the UI: this will be done this sprint and also needs to include tests for the ngrx data services (which will effectively replace the currently disabled unit tests for the *services.

- UI functional tests should be written for all UI components. So @kwk is right, we need tests for this. *But* let's wait for the meeting where @jarifibrahim can elaborate on how to write tests with the new test framework based on TS first. I'd say let's not unblock this PR, but be prepared that we need to focus writing tests this sprint and getting all together at the end of this iteration.

**Comment by fabric8cd** [comment]
@sahil143 fabric8/fabric8-ui:SNAPSHOT-PR-2440-2 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2440-fabric8-planner.badger.fabric8.io

**Comment by nimishamukherjee** [comment]
Also note that @Raunak1203 has written tests around planner table view. She is moving them to typescript. We can leverage that once it is ready.

**Comment by jarifibrahim** [comment]
@sahil143 @kwk @michaelkleinhenz 

> UI functional tests should be written for all UI components. So @kwk is right, we need tests for this. But let's wait for the meeting where @jarifibrahim can elaborate on how to write tests with the new test framework based on TS first. I'd say let's not unblock this PR, but be prepared that we need to focus writing tests this sprint and getting all together at the end of this iteration.

We can start writing **unit tests** for the components/services. We already have a lot of components/service that do not have any unit tests. UI functional tests won't test the code, they'll only test the functionality. Unit tests will validate the implementation details. At some point, we need to start writing unit tests as well.

**Comment by fabric8cd** [comment]
@sahil143 fabric8/fabric8-ui:SNAPSHOT-PR-2440-3 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2440-fabric8-planner.badger.fabric8.io

**Comment by sahil143** [comment]
> there's is an issue if we create a new workitem in new space. Steps:
-create a new space
-switch to flat view
-create a new work item
-now switch to tree view
-newly created workitem is not in the list.

@Raunak1203 this is fixed. Please verify

**Comment by fabric8cd** [comment]
@sahil143 fabric8/fabric8-ui:SNAPSHOT-PR-2440-4 is deployed and available for testing at https://fabric8-ui-fabric8-ui-pr-2440-fabric8-planner.badger.fabric8.io

**Comment by nimishamukherjee** [comment]
Will merge this PR as test day is coming up.

**Pull request merged**
